// GENERATED by npm run build:edge from server/ and src/engine — do not edit by hand.

// server/edge.ts
import { createClient } from "npm:@supabase/supabase-js@2";

// src/engine/catalog.ts
var CARD_DEFS = [
  // ── capitao ──
  { name: "Comandante Aurelion, Mestre da Forma\xE7\xE3o", cardType: "General", atk: 0, hp: 20, cost: 0, isFullArt: true, effect: "Ap\xF3s Remanejamento: at\xE9 2 unidades que se moveram ganham +1/+1 no pr\xF3ximo combate. Passiva: unidades adjacentes recebem -1 de dano." },
  { name: "Soldado T\xE1tico", cardType: "Infantaria", atk: 3, hp: 3, cost: 2, effect: "Troca com aliado adjacente no fim do turno." },
  { name: "Escudeiro de Linha", cardType: "Infantaria", atk: 2, hp: 4, cost: 2, effect: "Protege unidades atr\xE1s." },
  { name: "Capit\xE3o de Forma\xE7\xE3o", cardType: "Infantaria", atk: 3, hp: 4, cost: 3, isFullArt: true, effect: "Ao mover: adjacentes +1 ATK." },
  { name: "Batedor", cardType: "Infantaria", atk: 1, hp: 2, cost: 1, effect: "Move ap\xF3s combate." },
  { name: "Lanceiro de Controle", cardType: "Infantaria", atk: 3, hp: 2, cost: 2, effect: "Inimigo \xE0 sua frente recebe -1 ATK." },
  { name: "Cavaleiro T\xE1tico", cardType: "Cavalaria", atk: 4, hp: 4, cost: 3, isFullArt: true, effect: "Troca com qualquer aliado na linha." },
  { name: "Veterano de Guerra", cardType: "Infantaria", atk: 4, hp: 3, cost: 3, isFullArt: true, effect: "+2 ATK na coluna 3." },
  { name: "Reformar Linhas", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, isFullArt: true, effect: "Reorganiza at\xE9 3 unidades." },
  { name: "Avan\xE7o Coordenado", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, effect: "Ap\xF3s mover: +2 ATK." },
  { name: "Reposicionamento R\xE1pido", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Move inimigo 1 slot." },
  { name: "Linha Fechada", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, effect: "Adjacentes recebem menos dano." },
  { name: "Ordem de Retirada", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, effect: "Move para a Retaguarda + cura." },
  { name: "Bloqueio Instant\xE2neo", cardType: "Emboscada", atk: 0, hp: 0, cost: 2, effect: "Cancela ataque se houver adjacente." },
  { name: "Contra-Manobra", cardType: "Emboscada", atk: 0, hp: 0, cost: 3, isFullArt: true, effect: "Troca posi\xE7\xF5es durante o ataque." },
  { name: "Forma\xE7\xE3o Quebrada", cardType: "Emboscada", atk: 0, hp: 0, cost: 2, effect: "Move inimigo aleatoriamente." },
  { name: "Estandarte da Legi\xE3o", cardType: "Rel\xEDquia", atk: 0, hp: 5, cost: 3, isFullArt: true, effect: "Permanente. Todas as unidades aliadas ganham +1 ATK enquanto esta rel\xEDquia estiver no campo." },
  { name: "Fortaleza de Pedra", cardType: "Terreno", atk: 0, hp: 8, cost: 3, isFullArt: true, effect: "Permanente. Unidades aliadas na Retaguarda recebem -1 de dano de ataques inimigos." },
  { name: "P\xE2ntano Maldito", cardType: "Terreno", atk: 0, hp: 6, cost: 2, effect: "Permanente. Unidades inimigas na Vanguarda sofrem -1 ATK enquanto este terreno estiver no campo." },
  // ── cardeal ──
  { name: "Cardeal Pedro, Voz da F\xE9", cardType: "General", atk: 0, hp: 20, cost: 0, isFullArt: true, effect: "Fase Principal: pague 2 ouro para curar 1 HP em um soldado aliado, mesmo com HP cheio." },
  { name: "C\xE1lice da Gra\xE7a", cardType: "Rel\xEDquia", atk: 0, hp: 5, cost: 3, isFullArt: true, effect: "Permanente. A cura do General Cardeal Pedro aumenta de 1 para 2 HP." },
  { name: "Devotos da Cruzada", cardType: "Infantaria", atk: 0, hp: 3, cost: 1, effect: "\u2014" },
  { name: "Mercador da Cruzada", cardType: "Infantaria", atk: 1, hp: 1, cost: 1, effect: "Uma vez por turno: veja as 2 cartas do topo do deck. Adicione 1 \xE0 m\xE3o e coloque a outra no fundo." },
  { name: "Infiltrado da Ordem", cardType: "Infantaria", atk: 1, hp: 2, cost: 1, effect: "Na Vanguarda: impede Emboscadas inimigas. Se o General aliado receber dano, no pr\xF3ximo turno n\xE3o poder\xE1 usar sua habilidade." },
  { name: "Fan\xE1tico da Cruzada", cardType: "Infantaria", atk: 1, hp: 2, cost: 1, effect: "Ao atacar: se o General inimigo for de tipo oposto, ganha +2 ATK." },
  { name: "Recruta Devoto", cardType: "Infantaria", atk: 0, hp: 2, cost: 1, effect: "Ao ser curado: recebe +1 ATK permanente." },
  { name: "Intendente do Ex\xE9rcito", cardType: "Infantaria", atk: 2, hp: 3, cost: 2, effect: "Uma vez por turno: se voc\xEA tiver menos de 2 cartas na m\xE3o, compre at\xE9 ficar com 2." },
  { name: "Soldados da Ordem", cardType: "Infantaria", atk: 3, hp: 4, cost: 2, effect: "\u2014" },
  { name: "Jorge, Lan\xE7a Sagrada", cardType: "Cavalaria", atk: 4, hp: 6, cost: 3, isFullArt: true, effect: "Ao atacar a Vanguarda: causa 2 de dano \xE0 unidade na Retaguarda da mesma coluna." },
  { name: "Cavaleiro Hospital\xE1rio", cardType: "Cavalaria", atk: 2, hp: 3, cost: 2, effect: "Uma vez por turno: cure 1 HP de um aliado e cause 1 de dano a um inimigo na Vanguarda." },
  { name: "Nobre da Cruzada", cardType: "Cavalaria", atk: 4, hp: 5, cost: 3, isFullArt: true, effect: "Ao entrar em campo: invoca Soldados Leais (1 ATK / 1 HP) nos slots adjacentes livres da mesma fileira." },
  { name: "Cavaleiro da Luz", cardType: "Cavalaria", atk: 4, hp: 5, cost: 3, isFullArt: true, effect: "\u2014" },
  { name: "Comandante da Ordem", cardType: "Cavalaria", atk: 5, hp: 5, cost: 3, isFullArt: true, effect: "Na Vanguarda: Infantaria e Arqueiros aliados ganham +1 ATK e +1 HP durante o combate." },
  { name: "Arqueiro da Ordem", cardType: "Arqueiro", atk: 1, hp: 4, cost: 2, effect: "Pode atacar duas vezes por rodada." },
  { name: "Atirador da Cruzada", cardType: "Arqueiro", atk: 1, hp: 3, cost: 2, effect: "Ao ir ao cemit\xE9rio: compre 2 cartas." },
  { name: "Trabuco de Cerco", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 3, isFullArt: true, effect: "Causa 2 de dano a TODAS as unidades inimigas." },
  { name: "Catapulta de Guerra", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, effect: "Escolha uma fileira inimiga. Todas as unidades naquela fileira recebem 2 de dano." },
  { name: "Balestra de Precis\xE3o", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, effect: "Causa 3 de dano a uma unidade inimiga \xE0 sua escolha." },
  { name: "Armadura de Guerra", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Infantaria equipada recebe +2 HP." },
  { name: "Coura\xE7a Refor\xE7ada", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Arqueiro, Plebeu ou Infantaria equipada recebe +1 HP." },
  { name: "Flechas Venenosas", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Arqueiro equipado recebe +1 ATK." },
  { name: "Espada Longa", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Cavalaria, Infantaria ou Plebeu equipado recebe +2 ATK." },
  { name: "Refor\xE7os Ocultos", cardType: "Emboscada", atk: 0, hp: 0, cost: 1, effect: "Durante um ataque inimigo: um soldado aliado recebe +2 ATK e +1 HP at\xE9 o fim do turno." },
  { name: "Retorno do Soldado", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, isFullArt: true, effect: "Adicione um soldado do cemit\xE9rio \xE0 sua m\xE3o." },
  { name: "Graal da D\xE1diva", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Adicione uma carta de Terreno ou Rel\xEDquia do deck \xE0 sua m\xE3o." },
  { name: "Doutrina Renovada", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Adicione uma carta de T\xE1tica do deck \xE0 sua m\xE3o." },
  { name: "Recrutamento Seletivo", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 1, effect: "Adicione um soldado do deck \xE0 sua m\xE3o." },
  { name: "Recrutar Veteranos", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, effect: "Veja as 4 cartas do topo. Adicione 2 \xE0 m\xE3o e coloque 2 no fundo do deck." },
  { name: "Tributo de Guerra", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 0, effect: "Ganhe 1 ouro adicional neste turno." },
  { name: "Chamado \xE0s Armas", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 2, effect: "Invoque do deck at\xE9 2 soldados com 0 ATK para slots livres na Vanguarda. Embaralhe o deck." }
];
var DECK_RECIPES = {
  capitao: {
    id: "capitao",
    name: "Deck Capit\xE3o",
    description: "Infantaria disciplinada e reforma\xE7\xE3o t\xE1tica.",
    general: "Comandante Aurelion, Mestre da Forma\xE7\xE3o",
    cards: {
      "Soldado T\xE1tico": 4,
      "Escudeiro de Linha": 4,
      "Capit\xE3o de Forma\xE7\xE3o": 4,
      "Batedor": 4,
      "Lanceiro de Controle": 4,
      "Cavaleiro T\xE1tico": 4,
      "Veterano de Guerra": 3,
      "Reformar Linhas": 4,
      "Avan\xE7o Coordenado": 4,
      "Reposicionamento R\xE1pido": 4,
      "Linha Fechada": 4,
      "Ordem de Retirada": 4,
      "Bloqueio Instant\xE2neo": 4,
      "Contra-Manobra": 4,
      "Forma\xE7\xE3o Quebrada": 4,
      "Estandarte da Legi\xE3o": 1,
      "Fortaleza de Pedra": 1,
      "P\xE2ntano Maldito": 1
    }
  },
  cardeal: {
    id: "cardeal",
    name: "Deck Cardeal Pedro",
    description: "F\xE9 e ferro \u2014 cura, invoca\xE7\xF5es e emboscadas sagradas.",
    general: "Cardeal Pedro, Voz da F\xE9",
    cards: {
      "C\xE1lice da Gra\xE7a": 1,
      "Devotos da Cruzada": 4,
      "Mercador da Cruzada": 2,
      "Infiltrado da Ordem": 1,
      "Fan\xE1tico da Cruzada": 1,
      "Recruta Devoto": 2,
      "Intendente do Ex\xE9rcito": 2,
      "Soldados da Ordem": 2,
      "Jorge, Lan\xE7a Sagrada": 3,
      "Cavaleiro Hospital\xE1rio": 2,
      "Nobre da Cruzada": 2,
      "Cavaleiro da Luz": 4,
      "Comandante da Ordem": 1,
      "Arqueiro da Ordem": 2,
      "Atirador da Cruzada": 2,
      "Trabuco de Cerco": 2,
      "Catapulta de Guerra": 3,
      "Balestra de Precis\xE3o": 1,
      "Armadura de Guerra": 2,
      "Coura\xE7a Refor\xE7ada": 2,
      "Flechas Venenosas": 1,
      "Espada Longa": 2,
      "Refor\xE7os Ocultos": 2,
      "Retorno do Soldado": 1,
      "Graal da D\xE1diva": 1,
      "Doutrina Renovada": 2,
      "Recrutamento Seletivo": 2,
      "Recrutar Veteranos": 2,
      "Tributo de Guerra": 2,
      "Chamado \xE0s Armas": 2
    }
  }
};
var BY_NAME = {};
CARD_DEFS.forEach((c) => {
  BY_NAME[c.name] = c;
});
var getCardDef = (name) => BY_NAME[name];
var requireCardDef = (name) => {
  const def = BY_NAME[name];
  if (!def) throw new Error(`Unknown card: ${name}`);
  return def;
};
var isGeneralName = (name) => BY_NAME[name]?.cardType === "General";
var TOKEN_DEFS = [
  { name: "Soldado Leal", cardType: "Infantaria", atk: 1, hp: 1, cost: 0, effect: "" }
];
TOKEN_DEFS.forEach((c) => {
  BY_NAME[c.name] = c;
});

// src/engine/rng.ts
var seedFrom = (n) => n >>> 0 || 1;
var nextRandom = (holder) => {
  holder.rng = holder.rng + 1831565813 >>> 0;
  let t = holder.rng;
  t = Math.imul(t ^ t >>> 15, t | 1);
  t ^= t + Math.imul(t ^ t >>> 7, t | 61);
  return ((t ^ t >>> 14) >>> 0) / 4294967296;
};
var randomInt = (holder, maxExclusive) => Math.floor(nextRandom(holder) * maxExclusive);
var pickRandom = (holder, items) => items[randomInt(holder, items.length)];
var shuffled = (holder, items) => {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = randomInt(holder, i + 1);
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
};

// src/engine/rules.ts
var START_GOLD = 15;
var START_HAND = 7;
var GOLD_PER_TURN = 5;
var GOLD_FROM_ROUND = 2;
var HAND_LIMIT = 10;
var phasesForTurn = (combatOpen2) => combatOpen2 ? ["compra", "suprimentos", "preparacao", "combate", "pos_combate", "movimentacao"] : ["compra", "suprimentos", "preparacao", "movimentacao"];
var AUTOMATIC_PHASES = ["compra", "suprimentos"];
var restingPhasesForTurn = (combatOpen2) => phasesForTurn(combatOpen2).filter((p) => !AUTOMATIC_PHASES.includes(p));
var ABILITY_PHASES = {
  "Cardeal Pedro, Voz da F\xE9": ["preparacao", "pos_combate"],
  "Cavaleiro Hospital\xE1rio": ["preparacao", "pos_combate"]
};
var abilityPhases = (cardName) => ABILITY_PHASES[cardName] ?? ["preparacao"];
var REINFORCE_SHIELD = 2;
var canReinforce = (card) => !!card && card.cardType === "Infantaria";
var POST_COMBAT_CARD_TYPES = ["T\xE1tica", "Rel\xEDquia", "Terreno"];
var isFrontline = (slot) => slot >= 0 && slot <= 4;
var isBackline = (slot) => slot >= 5 && slot <= 9;
var isUnitSlot = (slot) => slot >= 0 && slot <= 9;
var getLaneCol = (slot) => {
  if (isFrontline(slot)) return slot;
  if (isBackline(slot)) return slot - 5;
  return -1;
};
var getMoveRow = (slot) => slot <= 4 ? 0 : 1;
var getMoveCol = (slot) => slot <= 4 ? slot : slot - 5;
var areSlotsAdjacent = (a, b) => {
  if (a < 0 || a > 9 || b < 0 || b > 9 || a === b) return false;
  return Math.abs(getMoveRow(a) - getMoveRow(b)) + Math.abs(getMoveCol(a) - getMoveCol(b)) === 1;
};
var adjacentSlots = (slot) => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].filter((j) => areSlotsAdjacent(slot, j));
var canReposition = (mover, from, to) => {
  if (!mover || from === to) return false;
  if (mover.name === "Cavaleiro T\xE1tico") return getMoveRow(from) === getMoveRow(to) && isUnitSlot(from) && isUnitSlot(to);
  return areSlotsAdjacent(from, to);
};
var SOLDIER_TYPES = ["Infantaria", "Cavalaria", "Arqueiro", "Artilharia"];
var TARGETABLE_TACTICS = {
  "Avan\xE7o Coordenado": "avanco_coordenado",
  "Reposicionamento R\xE1pido": "reposicionamento_rapido",
  "Linha Fechada": "linha_fechada",
  "Ordem de Retirada": "ordem_retirada",
  "Balestra de Precis\xE3o": "balesta",
  "Catapulta de Guerra": "catapulta",
  "Armadura de Guerra": "equip_armadura",
  "Coura\xE7a Refor\xE7ada": "equip_corcelete",
  "Flechas Venenosas": "equip_flecha",
  "Espada Longa": "equip_espada"
};
var ENEMY_TARGET_KINDS = /* @__PURE__ */ new Set(["reposicionamento_rapido", "balesta", "catapulta"]);
var EQUIP_ALLOWED_TYPES = {
  equip_armadura: ["Infantaria"],
  equip_corcelete: ["Arqueiro", "Infantaria"],
  equip_flecha: ["Arqueiro"],
  equip_espada: ["Cavalaria", "Infantaria"]
};
var IMMEDIATE_CARD_NAMES = /* @__PURE__ */ new Set([
  "Reformar Linhas",
  "Tributo de Guerra",
  "Trabuco de Cerco",
  "Retorno do Soldado",
  "Graal da D\xE1diva",
  "Doutrina Renovada",
  "Recrutamento Seletivo",
  "Recrutar Veteranos",
  "Chamado \xE0s Armas"
]);
var getCardDropKind = (card) => {
  if (IMMEDIATE_CARD_NAMES.has(card.name)) return "immediate";
  const kind = TARGETABLE_TACTICS[card.name];
  if (kind) return ENEMY_TARGET_KINDS.has(kind) ? "enemyTarget" : "ownTarget";
  if (card.cardType === "Emboscada" || card.cardType === "T\xE1tica") return "blocked";
  return "place";
};
var canPlaceInSlot = (cardType, slot) => {
  if (slot < 0 || slot >= 12) return false;
  if (cardType === "Emboscada" || cardType === "T\xE1tica" || cardType === "General") return false;
  if (cardType === "Rel\xEDquia") return slot === 10;
  if (cardType === "Terreno") return slot === 11;
  return slot <= 9;
};
var isAliveAt = (board, slot, name) => board[slot]?.name === name;
var isCardDamaged = (card) => card.hp < (getCardDef(card.name)?.hp ?? card.hp);
var hasLiderBuff = (card, own) => {
  if (card.cardType !== "Infantaria" && card.cardType !== "Arqueiro") return false;
  return [0, 1, 2, 3, 4].some((i) => own[i]?.name === "Comandante da Ordem");
};
var getAuraCombatHpBonus = (card, own) => hasLiderBuff(card, own) ? 1 : 0;
var hasEspiaoInVanguarda = (board) => [0, 1, 2, 3, 4].some((i) => board[i]?.name === "Infiltrado da Ordem");
var hasEspiaoOnBoard = (board) => [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].some((i) => board[i]?.name === "Infiltrado da Ordem");
var getMaxAttacksPerTurn = (card) => card.name === "Arqueiro da Ordem" ? 2 : 1;
var getEffectiveAtk = (card, ownIndex, own, enemy) => {
  let atk = card.atk + (card.pendingCombatBonus?.atk ?? 0);
  atk += card.formationBuffAtk ?? 0;
  if (isAliveAt(own, 10, "Estandarte da Legi\xE3o")) atk += 1;
  if (card.name === "Veterano de Guerra" && getLaneCol(ownIndex) === 2) atk += 2;
  const facing = enemy[ownIndex];
  if (facing && facing.name === "Lanceiro de Controle") atk -= 1;
  if (isFrontline(ownIndex) && isAliveAt(enemy, 11, "P\xE2ntano Maldito")) atk -= 1;
  if (hasLiderBuff(card, own)) atk += 1;
  return Math.max(0, atk);
};
var getIncomingDamageReduction = (ownIndex, own) => {
  let reduction = 0;
  if ((ownIndex === 10 || ownIndex === 11) && isAliveAt(own, 12, "Comandante Aurelion, Mestre da Forma\xE7\xE3o")) reduction += 1;
  if (isBackline(ownIndex) && isAliveAt(own, 11, "Fortaleza de Pedra")) reduction += 1;
  reduction += own[ownIndex]?.dmgReduction ?? 0;
  return reduction;
};
var getValidAttackTargets = (attackerIndex, attackerBoard, enemyBoard) => {
  const valid = /* @__PURE__ */ new Set();
  const attacker = attackerBoard[attackerIndex];
  if (!attacker) return valid;
  const attackerCol = getLaneCol(attackerIndex);
  if (attackerCol === -1) return valid;
  if (attacker.cardType === "Infantaria" && isBackline(attackerIndex)) return valid;
  const isRanged = attacker.cardType === "Arqueiro" || attacker.cardType === "Artilharia";
  const directFrontal = !isRanged && !!enemyBoard[attackerCol];
  const scanCols = directFrontal ? [attackerCol] : [attackerCol - 1, attackerCol, attackerCol + 1].filter((c) => c >= 0 && c <= 4);
  scanCols.forEach((col) => {
    if (enemyBoard[col]) valid.add(col);
    else if (enemyBoard[col + 5]) valid.add(col + 5);
  });
  [{ col: 1, target: 10 }, { col: 2, target: 12 }, { col: 3, target: 11 }].forEach(({ col, target }) => {
    if (!enemyBoard[target] || !scanCols.includes(col)) return;
    if (!enemyBoard[col] && !enemyBoard[col + 5]) valid.add(target);
  });
  return valid;
};
var withEquippedWeapons = (cards) => cards.flatMap((c) => c.equippedWeapons?.length ? [{ ...c, equippedWeapons: void 0 }, ...c.equippedWeapons] : [c]);

// src/engine/types.ts
var otherSeat = (s) => s === 0 ? 1 : 0;
var SLOT_COUNT = 13;
var GENERAL_SLOT = 12;

// src/engine/game.ts
var expandCards = (cards) => Array.isArray(cards) ? [...cards] : Object.entries(cards).flatMap(([name, n]) => Array(n).fill(name));
var cardFromName = (s, name, prefix = "c") => {
  const def = requireCardDef(name);
  s.uid += 1;
  const card = { id: `${prefix}${s.uid}`, name: def.name, cardType: def.cardType, atk: def.atk, hp: def.hp, cost: def.cost, effect: def.effect };
  if (def.isFullArt) card.isFullArt = true;
  return card;
};
var createMatch = (opts) => {
  const mkPlayer = (setup) => ({
    gold: START_GOLD,
    hand: [],
    board: Array(SLOT_COUNT).fill(null),
    graveyard: [],
    deckList: expandCards(setup.cards),
    drawPile: [],
    general: setup.general,
    generalAbilityUses: 0,
    generalAbilityBlocked: false,
    pendingGeneralBlock: false
  });
  const s = {
    v: 1,
    rng: seedFrom(opts.seed),
    uid: 0,
    players: [mkPlayer(opts.decks[0]), mkPlayer(opts.decks[1])],
    turn: {
      started: false,
      active: opts.first,
      round: 1,
      phase: "preparacao",
      first: opts.first,
      moved: [],
      bonusRepositions: 0,
      batedorFree: null,
      attackCounts: {},
      activated: []
    },
    pending: null,
    winner: null
  };
  const c = { s, ev: [] };
  [0, 1].forEach((seat) => {
    const p = s.players[seat];
    p.board[GENERAL_SLOT] = cardFromName(s, p.general, "g");
    for (let i = 0; i < START_HAND; i++) drawCards(c, seat, 1, "deal");
  });
  return { state: s, events: c.ev };
};
var RuleError = class extends Error {
};
var fail = (message) => {
  throw new RuleError(message);
};
var log = (c, seat, text, priv = false) => {
  c.ev.push(priv ? { t: "log", seat, text, private: true } : { t: "log", seat, text });
};
var P = (c, seat) => c.s.players[seat];
var combatOpen = (s) => s.turn.round >= 2 || s.turn.active !== s.turn.first;
var activePhases = (s) => restingPhasesForTurn(combatOpen(s));
var addGold = (c, seat, delta, reason) => {
  if (delta === 0) return;
  P(c, seat).gold += delta;
  c.ev.push({ t: "gold", seat, delta, reason });
};
var drawCards = (c, seat, n, reason) => {
  const p = P(c, seat);
  for (let i = 0; i < n; i++) {
    if (p.drawPile.length === 0) p.drawPile = shuffled(c.s, p.deckList);
    const name = p.drawPile.shift();
    if (!name) return;
    const card = cardFromName(c.s, name, "h");
    p.hand.push(card);
    c.ev.push({ t: "draw", seat, card, reason });
  }
};
var removeFromHand = (c, seat, cardId) => {
  const hand = P(c, seat).hand;
  const i = hand.findIndex((h) => h.id === cardId);
  if (i === -1) return fail("Essa carta n\xE3o est\xE1 na sua m\xE3o.");
  return hand.splice(i, 1)[0];
};
var discard = (c, seat, card) => {
  P(c, seat).graveyard.push(card);
  c.ev.push({ t: "graveyard", seat, card });
};
var sendDestroyed = (c, seat, entries) => {
  if (entries.length === 0) return;
  const p = P(c, seat);
  entries.forEach(({ slot, card }) => c.ev.push({ t: "destroyed", seat, slot, card }));
  const cards = entries.map((e) => e.card);
  withEquippedWeapons(cards).forEach((card) => {
    p.graveyard.push(card);
    c.ev.push({ t: "graveyard", seat, card });
  });
  const atiradores = cards.filter((card) => card.name === "Atirador da Cruzada").length;
  if (atiradores > 0) drawCards(c, seat, atiradores * 2, "effect");
  if (cards.some((card) => card.cardType === "General")) setWinner(c, otherSeat(seat));
  reinforceFrom(c, seat, entries.map((e) => e.slot));
};
var reinforceFrom = (c, seat, fallenSlots) => {
  if (c.s.winner !== null) return;
  const board = P(c, seat).board;
  [...fallenSlots].sort((a, b) => a - b).forEach((slot) => {
    if (slot < 0 || slot > 4 || board[slot]) return;
    const behind = board[slot + 5];
    if (!canReinforce(behind)) return;
    const moved = { ...behind };
    board[slot] = moved;
    board[slot + 5] = null;
    c.ev.push({ t: "reinforce", seat, from: slot + 5, to: slot, card: moved });
    grantShield(c, seat, slot, REINFORCE_SHIELD);
    log(c, seat, `Refor\xE7o! ${moved.name} avan\xE7ou para a Vanguarda com Escudo ${REINFORCE_SHIELD}.`);
  });
};
var setWinner = (c, seat) => {
  if (c.s.winner !== null) return;
  c.s.winner = seat;
  c.ev.push({ t: "winner", seat });
};
var soak = (c, seat, slot, card, amount) => {
  if (amount <= 0 || !card.block && !(card.shield && card.shield > 0)) return { card, through: Math.max(0, amount) };
  if (card.block) {
    c.ev.push({ t: "shield_hit", seat, slot, absorbed: amount, left: card.shield ?? 0, broken: false, blocked: true });
    return { card: { ...card, block: void 0 }, through: 0 };
  }
  const absorbed = Math.min(card.shield, amount);
  const left = card.shield - absorbed;
  c.ev.push({ t: "shield_hit", seat, slot, absorbed, left, broken: left === 0, blocked: false });
  return { card: { ...card, shield: left > 0 ? left : void 0 }, through: amount - absorbed };
};
var grantShield = (c, seat, slot, amount) => {
  const board = P(c, seat).board;
  const card = board[slot];
  if (!card || amount <= 0) return;
  board[slot] = { ...card, shield: (card.shield ?? 0) + amount };
  c.ev.push({ t: "shield", seat, slot, shield: amount, block: false });
};
var damageSlot = (c, seat, slot, amount) => {
  const board = P(c, seat).board;
  const card = board[slot];
  if (!card) return null;
  const soaked = soak(c, seat, slot, card, amount);
  if (soaked.through > 0 || amount === 0) c.ev.push({ t: "damage", seat, slot, amount: soaked.through });
  const hp = soaked.card.hp - soaked.through;
  if (hp <= 0) {
    board[slot] = null;
    return { slot, card: { ...soaked.card, hp } };
  }
  board[slot] = { ...soaked.card, hp };
  return null;
};
var healSlot = (c, seat, slot, amount) => {
  const board = P(c, seat).board;
  const card = board[slot];
  let healed = { ...card, hp: card.hp + amount };
  if (healed.name === "Recruta Devoto") healed = { ...healed, atk: healed.atk + 1 };
  board[slot] = healed;
  c.ev.push({ t: "heal", seat, slot, amount });
};
var applyNobreSummon = (c, seat, slot) => {
  const board = P(c, seat).board;
  if (board[slot]?.name !== "Nobre da Cruzada" || slot > 9) return;
  [slot - 1, slot + 1].forEach((j) => {
    if (areSlotsAdjacent(slot, j) && !board[j]) {
      const token = cardFromName(c.s, "Soldado Leal", "t");
      board[j] = token;
      c.ev.push({ t: "summon", seat, slot: j, card: token });
    }
  });
};
var applyFormationCaptainBuff = (c, seat, slot) => {
  const board = P(c, seat).board;
  if (board[slot]?.name !== "Capit\xE3o de Forma\xE7\xE3o") return;
  adjacentSlots(slot).forEach((j) => {
    if (board[j]) {
      board[j] = { ...board[j], formationBuffAtk: (board[j].formationBuffAtk ?? 0) + 1 };
      c.ev.push({ t: "buff", seat, slot: j, atk: 1, hp: 0 });
    }
  });
};
var startTurn = (c, seat) => {
  const t = c.s.turn;
  const p = P(c, seat);
  t.active = seat;
  t.phase = "compra";
  t.moved = [];
  t.bonusRepositions = 0;
  t.batedorFree = null;
  t.attackCounts = {};
  t.activated = [];
  c.ev.push({ t: "turn_start", seat, round: t.round });
  p.board.forEach((card, i) => {
    if (card?.formationBuffAtk) p.board[i] = { ...card, formationBuffAtk: 0 };
  });
  p.generalAbilityUses = 0;
  p.generalAbilityBlocked = p.pendingGeneralBlock;
  p.pendingGeneralBlock = false;
  const skip = p.skip ?? {};
  p.skip = void 0;
  c.ev.push({ t: "phase", seat, phase: "compra" });
  if (skip.compra) {
    c.ev.push({ t: "skip", seat, phase: "compra" });
    log(c, seat, "A fase de Compra foi pulada!");
  } else {
    drawCards(c, seat, 1, "turn");
    if (p.board.some((card, i) => i <= 9 && card?.name === "Intendente do Ex\xE9rcito") && p.hand.length < 2) {
      drawCards(c, seat, 2 - p.hand.length, "effect");
    }
  }
  t.phase = "suprimentos";
  c.ev.push({ t: "phase", seat, phase: "suprimentos" });
  if (skip.suprimentos) {
    c.ev.push({ t: "skip", seat, phase: "suprimentos" });
    log(c, seat, "A fase de Suprimentos foi pulada!");
  } else if (t.round >= GOLD_FROM_ROUND) {
    addGold(c, seat, GOLD_PER_TURN, "turn");
  }
  t.phase = "preparacao";
  c.ev.push({ t: "phase", seat, phase: "preparacao" });
};
var grantAurelionBuff = (c, seat) => {
  const board = P(c, seat).board;
  if (board[GENERAL_SLOT]?.name !== "Comandante Aurelion, Mestre da Forma\xE7\xE3o" || c.s.turn.moved.length === 0) return;
  c.s.turn.moved.filter((i) => board[i]).slice(0, 2).forEach((i) => {
    board[i] = { ...board[i], pendingCombatBonus: { atk: 1, hp: 1 } };
    c.ev.push({ t: "buff", seat, slot: i, atk: 1, hp: 1 });
  });
};
var applyEndOfTurnSwaps = (c, seat) => {
  const board = P(c, seat).board;
  const settled = /* @__PURE__ */ new Set();
  for (let i = 0; i <= 9; i++) {
    if (settled.has(i) || board[i]?.name !== "Soldado T\xE1tico") continue;
    const partner = [i - 1, i + 1, i - 5, i + 5].find((j) => areSlotsAdjacent(i, j) && board[j] && !settled.has(j));
    if (partner !== void 0) {
      [board[i], board[partner]] = [board[partner], board[i]];
      settled.add(i);
      settled.add(partner);
      c.ev.push({ t: "move", seat, from: i, to: partner, swapped: true });
    }
  }
};
var endTurn = (c) => {
  const t = c.s.turn;
  const seat = t.active;
  grantAurelionBuff(c, seat);
  applyEndOfTurnSwaps(c, seat);
  if (seat !== t.first) t.round += 1;
  startTurn(c, otherSeat(seat));
};
var assertCanAct = (c, seat, allowPending = false) => {
  const s = c.s;
  if (s.winner !== null) fail("A partida j\xE1 terminou.");
  if (!s.turn.started) fail("A partida ainda n\xE3o come\xE7ou.");
  if (s.turn.active !== seat) fail("N\xE3o \xE9 o seu turno.");
  if (s.pending && !allowPending) fail("Responda \xE0 escolha pendente primeiro.");
};
var uniqueByName = (names) => [...new Set(names)];
var playCard = (c, seat, a) => {
  assertCanAct(c, seat);
  const p = P(c, seat);
  const enemySeat = otherSeat(seat);
  const enemy = P(c, enemySeat);
  const card = p.hand.find((h) => h.id === a.cardId);
  if (!card) return fail("Essa carta n\xE3o est\xE1 na sua m\xE3o.");
  const phase = c.s.turn.phase;
  const inMovement = phase === "movimentacao" && card.name === "Avan\xE7o Coordenado";
  if (phase === "pos_combate") {
    if (!POST_COMBAT_CARD_TYPES.includes(card.cardType)) fail("Depois do combate s\xF3 d\xE1 pra jogar T\xE1ticas, Rel\xEDquias e Terrenos!");
  } else if (phase !== "preparacao" && !inMovement) {
    fail("Jogar cartas s\xF3 nas fases de Prepara\xE7\xE3o e P\xF3s-combate!");
  }
  if (p.gold < card.cost) fail("Ouro insuficiente!");
  const commit = () => {
    removeFromHand(c, seat, card.id);
    addGold(c, seat, -card.cost, "spend");
    c.ev.push({ t: "play", seat, card });
  };
  const toGraveyard = () => discard(c, seat, card);
  const openPick = (mode, title, options, min, max, extra = {}) => {
    c.s.pending = { kind: "pick", seat, mode, title, options, min, max, source: card, ...extra };
    c.ev.push({ t: "pick", seat, title });
  };
  const optionsFromNames = (names) => uniqueByName(names).map((n) => cardFromName(c.s, n, "o"));
  const requireTarget = (needsSlot, message) => {
    if (needsSlot === void 0) return fail(message);
    return needsSlot;
  };
  const kind = getCardDropKind(card);
  if (kind === "place") {
    const slot2 = requireTarget(a.slot, "Escolha um slot para a carta.");
    if (slot2 === 12) fail("O General n\xE3o pode ser substitu\xEDdo!");
    if ((slot2 === 10 || slot2 === 11) && card.cardType !== "Rel\xEDquia" && card.cardType !== "Terreno") fail("Esse slot \xE9 s\xF3 para Rel\xEDquia ou Terreno!");
    if (slot2 <= 9 && (card.cardType === "Rel\xEDquia" || card.cardType === "Terreno")) fail("Rel\xEDquia/Terreno s\xF3 pode ir no slot especial ao lado do General!");
    if (card.cardType === "Rel\xEDquia" && slot2 !== 10) fail("A Rel\xEDquia vai no slot especial da esquerda do General.");
    if (card.cardType === "Terreno" && slot2 !== 11) fail("O Terreno vai no slot especial da direita do General.");
    if (!canPlaceInSlot(card.cardType, slot2)) fail("Esse slot n\xE3o aceita essa carta.");
    if (p.board[slot2]) fail("Esse slot j\xE1 est\xE1 ocupado!");
    commit();
    p.board[slot2] = card;
    c.ev.push({ t: "place", seat, slot: slot2, card });
    applyNobreSummon(c, seat, slot2);
    return;
  }
  if (kind === "blocked") {
    if (card.cardType === "Emboscada") fail("Emboscadas ativam sozinhas quando voc\xEA \xE9 atacado \u2014 mantenha na m\xE3o.");
    fail("Essa T\xE1tica ainda n\xE3o pode ser jogada.");
  }
  if (kind === "immediate") {
    switch (card.name) {
      case "Reformar Linhas":
        commit();
        toGraveyard();
        c.s.turn.bonusRepositions += 3;
        log(c, seat, "Reformar Linhas: +3 reposicionamentos b\xF4nus neste turno!");
        return;
      case "Tributo de Guerra":
        commit();
        toGraveyard();
        addGold(c, seat, 1, "gain");
        log(c, seat, "Tributo de Guerra: +1 ouro neste turno!");
        return;
      case "Trabuco de Cerco": {
        commit();
        toGraveyard();
        const dead = [];
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12].forEach((i) => {
          const d = damageSlot(c, enemySeat, i, 2);
          if (d) dead.push(d);
        });
        log(c, seat, "Trabuco de Cerco: 2 de dano a todas as unidades inimigas!");
        sendDestroyed(c, enemySeat, dead);
        return;
      }
      case "Retorno do Soldado": {
        const options = p.graveyard.filter((g) => SOLDIER_TYPES.includes(g.cardType));
        if (options.length === 0) fail("N\xE3o h\xE1 soldados no cemit\xE9rio.");
        commit();
        openPick("graveyard_soldier", "Escolha um soldado do cemit\xE9rio para adicionar \xE0 m\xE3o", options, 1, 1);
        return;
      }
      case "Graal da D\xE1diva": {
        const names = p.deckList.filter((n) => {
          const t = getCardDef(n)?.cardType;
          return t === "Terreno" || t === "Rel\xEDquia";
        });
        if (names.length === 0) fail("N\xE3o h\xE1 Terreno ou Rel\xEDquia no deck.");
        commit();
        openPick("deck_search", "Escolha uma carta de Terreno ou Rel\xEDquia do deck", optionsFromNames(names), 1, 1);
        return;
      }
      case "Doutrina Renovada": {
        const names = p.deckList.filter((n) => getCardDef(n)?.cardType === "T\xE1tica");
        if (names.length === 0) fail("N\xE3o h\xE1 T\xE1ticas no deck.");
        commit();
        openPick("deck_search", "Escolha uma T\xE1tica do deck para adicionar \xE0 m\xE3o", optionsFromNames(names), 1, 1);
        return;
      }
      case "Recrutamento Seletivo": {
        const names = p.deckList.filter((n) => SOLDIER_TYPES.includes(getCardDef(n).cardType));
        if (names.length === 0) fail("N\xE3o h\xE1 soldados no deck.");
        commit();
        openPick("deck_search", "Escolha um soldado do deck para adicionar \xE0 m\xE3o", optionsFromNames(names), 1, 1);
        return;
      }
      case "Recrutar Veteranos": {
        commit();
        if (p.drawPile.length < 4) p.drawPile = [...p.drawPile, ...shuffled(c.s, p.deckList)];
        const revealed = p.drawPile.splice(0, 4).map((n) => cardFromName(c.s, n, "o"));
        openPick("top_reveal", "Veja as 4 cartas do topo \u2014 escolha 2 para a m\xE3o", revealed, 1, 2, { revealed: true });
        return;
      }
      case "Chamado \xE0s Armas": {
        const names = p.deckList.filter((n) => {
          const d = getCardDef(n);
          return SOLDIER_TYPES.includes(d.cardType) && d.atk === 0;
        });
        const slots = [0, 1, 2, 3, 4].filter((i) => !p.board[i]);
        if (names.length === 0) fail("N\xE3o h\xE1 soldados de 0 ATK no deck.");
        if (slots.length === 0) fail("N\xE3o h\xE1 slots livres na Vanguarda.");
        commit();
        const max = Math.min(2, slots.length);
        openPick("summon", `Escolha at\xE9 ${max} soldado(s) de 0 ATK para invocar na Vanguarda`, optionsFromNames(names), 1, max, { slots });
        return;
      }
      default:
        fail("Essa T\xE1tica ainda n\xE3o pode ser jogada.");
    }
  }
  const tactic = TARGETABLE_TACTICS[card.name];
  const slot = requireTarget(a.target, "Escolha um alvo no campo.");
  const own = p.board;
  const foe = enemy.board;
  if (tactic === "avanco_coordenado") {
    if (slot > 9 || !own[slot]) fail("Escolha uma unidade sua no campo.");
    if (!c.s.turn.moved.includes(slot)) fail("Essa unidade n\xE3o se moveu neste turno.");
    commit();
    toGraveyard();
    own[slot] = { ...own[slot], atk: own[slot].atk + 2 };
    c.ev.push({ t: "buff", seat, slot, atk: 2, hp: 0 });
    log(c, seat, `${own[slot].name} recebeu +2 ATK!`);
  } else if (tactic === "linha_fechada") {
    if (slot > 9 || !own[slot]) fail("Escolha uma unidade sua no campo.");
    commit();
    toGraveyard();
    adjacentSlots(slot).forEach((j) => {
      if (own[j]) own[j] = { ...own[j], dmgReduction: (own[j].dmgReduction ?? 0) + 1 };
    });
    log(c, seat, "Linha Fechada: aliados adjacentes recebem menos dano!");
  } else if (tactic === "ordem_retirada") {
    if (!isFrontline(slot) || !own[slot]) fail("Escolha uma unidade sua na Vanguarda.");
    const back = slot + 5;
    if (own[back]) fail("A Retaguarda dessa coluna j\xE1 est\xE1 ocupada.");
    commit();
    toGraveyard();
    const moved = { ...own[slot], hp: own[slot].hp + 2 };
    own[back] = moved;
    own[slot] = null;
    c.ev.push({ t: "move", seat, from: slot, to: back, swapped: false });
    c.ev.push({ t: "heal", seat, slot: back, amount: 2 });
    log(c, seat, `${moved.name} recuou para a Retaguarda e recuperou 2 HP!`);
  } else if (tactic === "equip_armadura" || tactic === "equip_corcelete" || tactic === "equip_flecha" || tactic === "equip_espada") {
    const allowed = EQUIP_ALLOWED_TYPES[tactic];
    const target = own[slot];
    if (slot > 9 || !target || !allowed.includes(target.cardType)) fail(`Escolha uma unidade do tipo certo: ${allowed.join(" ou ")}.`);
    commit();
    const atkBonus = tactic === "equip_flecha" ? 1 : tactic === "equip_espada" ? 2 : 0;
    const hpBonus = tactic === "equip_armadura" ? 2 : tactic === "equip_corcelete" ? 1 : 0;
    own[slot] = { ...target, atk: target.atk + atkBonus, hp: target.hp + hpBonus, equippedWeapons: [...target.equippedWeapons ?? [], card] };
    c.ev.push({ t: "equip", seat, slot, card, atk: atkBonus, hp: hpBonus });
    log(c, seat, `${target.name} equipado: ${card.name}!`);
  } else if (tactic === "reposicionamento_rapido") {
    if (slot > 9 || !foe[slot]) fail("Escolha uma unidade inimiga no campo.");
    commit();
    toGraveyard();
    const free = adjacentSlots(slot).filter((j) => !foe[j]);
    if (free.length > 0) {
      const dest = pickRandom(c.s, free);
      foe[dest] = foe[slot];
      foe[slot] = null;
      c.ev.push({ t: "move", seat: enemySeat, from: slot, to: dest, swapped: false });
      log(c, seat, "Reposicionamento R\xE1pido: unidade inimiga deslocada!");
    } else {
      log(c, seat, "N\xE3o havia slot livre adjacente para deslocar a unidade.");
    }
  } else if (tactic === "balesta") {
    if (slot > 9 || !foe[slot]) fail("Escolha uma unidade inimiga no campo.");
    commit();
    toGraveyard();
    const d = damageSlot(c, enemySeat, slot, 3);
    log(c, seat, "Balestra de Precis\xE3o: 3 de dano causado!");
    if (d) sendDestroyed(c, enemySeat, [d]);
  } else if (tactic === "catapulta") {
    if (slot > 9) fail("Escolha uma fileira inimiga (Vanguarda ou Retaguarda).");
    commit();
    toGraveyard();
    const row = getMoveRow(slot) === 0 ? [0, 1, 2, 3, 4] : [5, 6, 7, 8, 9];
    const dead = [];
    row.forEach((i) => {
      const d = damageSlot(c, enemySeat, i, 2);
      if (d) dead.push(d);
    });
    log(c, seat, "Catapulta de Guerra: 2 de dano em toda a fileira!");
    sendDestroyed(c, enemySeat, dead);
  } else {
    fail("Essa T\xE1tica ainda n\xE3o pode ser jogada.");
  }
};
var useAbility = (c, seat, a) => {
  assertCanAct(c, seat);
  const p = P(c, seat);
  const enemySeat = otherSeat(seat);
  const card = p.board[a.slot];
  if (!card) return fail("N\xE3o h\xE1 carta nesse slot.");
  if (!abilityPhases(card.name).includes(c.s.turn.phase)) {
    fail(abilityPhases(card.name).includes("pos_combate") ? "Essa habilidade s\xF3 vale na Prepara\xE7\xE3o e no P\xF3s-combate." : "Habilidades s\xF3 na fase de Prepara\xE7\xE3o.");
  }
  const usedUp = c.s.turn.activated.includes(card.id);
  if (a.slot === GENERAL_SLOT) {
    if (card.name !== "Cardeal Pedro, Voz da F\xE9") fail("Esse General n\xE3o tem habilidade ativa.");
    if (p.generalAbilityUses >= 1) fail("A habilidade do General j\xE1 foi usada neste turno.");
    if (p.generalAbilityBlocked) fail("Infiltrado da Ordem: a habilidade do General est\xE1 bloqueada neste turno.");
    if (p.gold < 2) fail("Ouro insuficiente!");
    const target = a.target;
    if (target === void 0 || target > 9 || !p.board[target]) fail("Escolha um soldado aliado no campo.");
    const amount = p.board[10]?.name === "C\xE1lice da Gra\xE7a" ? 2 : 1;
    addGold(c, seat, -2, "spend");
    p.generalAbilityUses += 1;
    c.ev.push({ t: "ability", seat, slot: a.slot, name: card.name });
    healSlot(c, seat, target, amount);
    log(c, seat, `${p.board[target].name} recuperou ${amount} HP!`);
    return;
  }
  if (!isUnitSlot(a.slot)) fail("Essa carta n\xE3o tem habilidade ativa.");
  if (card.name === "Mercador da Cruzada") {
    if (usedUp) fail("Essa habilidade j\xE1 foi usada neste turno.");
    c.s.turn.activated.push(card.id);
    c.ev.push({ t: "ability", seat, slot: a.slot, name: card.name });
    if (p.drawPile.length < 2) p.drawPile = [...p.drawPile, ...shuffled(c.s, p.deckList)];
    const revealed = p.drawPile.splice(0, 2).map((n) => cardFromName(c.s, n, "o"));
    const title = "Mercador da Cruzada: veja as 2 cartas do topo \u2014 escolha 1 para a m\xE3o";
    c.s.pending = { kind: "pick", seat, mode: "top_reveal", title, options: revealed, min: 1, max: 1, source: null, revealed: true };
    c.ev.push({ t: "pick", seat, title });
    return;
  }
  if (card.name === "Cavaleiro Hospital\xE1rio") {
    if (usedUp) fail("Essa habilidade j\xE1 foi usada neste turno.");
    const foe = P(c, enemySeat).board;
    const hasDamaged = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].some((i) => p.board[i] && isCardDamaged(p.board[i]));
    const hasEnemyFront = [0, 1, 2, 3, 4].some((i) => foe[i]);
    if (!hasDamaged && !hasEnemyFront) fail("Cavaleiro Hospital\xE1rio: nenhum alvo dispon\xEDvel.");
    if (hasDamaged) {
      const t1 = a.target;
      if (t1 === void 0 || t1 > 9 || !p.board[t1] || !isCardDamaged(p.board[t1])) fail("Escolha um aliado ferido no campo.");
    }
    if (hasEnemyFront) {
      const t2 = a.target2;
      if (t2 === void 0 || !isFrontline(t2) || !foe[t2]) fail("Escolha um inimigo na Vanguarda.");
    }
    c.s.turn.activated.push(card.id);
    c.ev.push({ t: "ability", seat, slot: a.slot, name: card.name });
    if (hasDamaged) {
      healSlot(c, seat, a.target, 1);
      log(c, seat, `${p.board[a.target].name} recuperou 1 HP!`);
    }
    if (hasEnemyFront) {
      const d = damageSlot(c, enemySeat, a.target2, 1);
      log(c, seat, "Cavaleiro Hospital\xE1rio causou 1 de dano!");
      if (d) sendDestroyed(c, enemySeat, [d]);
    }
    return;
  }
  fail("Essa carta n\xE3o tem habilidade ativa.");
};
var choose = (c, seat, a) => {
  const pend = c.s.pending;
  if (!pend || pend.kind !== "pick") return fail("N\xE3o h\xE1 nenhuma escolha pendente.");
  if (pend.seat !== seat) return fail("Essa escolha n\xE3o \xE9 sua.");
  const ids = a.cardIds;
  if (new Set(ids).size !== ids.length) fail("Escolha cartas diferentes.");
  if (ids.length < pend.min || ids.length > pend.max) fail(`Escolha ${pend.min === pend.max ? pend.max : `de ${pend.min} a ${pend.max}`} carta(s).`);
  const picked = ids.map((id) => pend.options.find((o) => o.id === id) ?? fail("Carta inv\xE1lida para essa escolha."));
  const p = P(c, seat);
  c.s.pending = null;
  const toHand = (card) => {
    const copy = cardFromName(c.s, card.name, "h");
    p.hand.push(copy);
    c.ev.push({ t: "draw", seat, card: copy, reason: "effect" });
  };
  if (pend.mode === "graveyard_soldier") {
    const chosen = picked[0];
    p.graveyard = p.graveyard.filter((g) => g.id !== chosen.id);
    toHand(chosen);
    log(c, seat, `${chosen.name} voltou para sua m\xE3o!`);
  } else if (pend.mode === "deck_search") {
    toHand(picked[0]);
    log(c, seat, `${picked[0].name} adicionada \xE0 m\xE3o!`, true);
  } else if (pend.mode === "top_reveal") {
    picked.forEach(toHand);
    const pickedIds = new Set(picked.map((x) => x.id));
    p.drawPile.push(...pend.options.filter((o) => !pickedIds.has(o.id)).map((o) => o.name));
    log(c, seat, `${picked.length} carta(s) adicionada(s) \xE0 m\xE3o!`);
  } else if (pend.mode === "summon") {
    const slots = pend.slots ?? [];
    picked.forEach((card, i) => {
      const slot = slots[i];
      if (slot === void 0 || p.board[slot]) return;
      const copy = cardFromName(c.s, card.name, "h");
      p.board[slot] = copy;
      c.ev.push({ t: "summon", seat, slot, card: copy });
    });
    p.drawPile = shuffled(c.s, p.deckList);
    log(c, seat, `${picked.length} soldado(s) invocado(s)! Deck embaralhado.`);
  }
  if (pend.source) discard(c, seat, pend.source);
};
var attack = (c, seat, a) => {
  assertCanAct(c, seat);
  const t = c.s.turn;
  if (t.phase !== "combate") fail("Ataques s\xF3 na fase de Combate!");
  const p = P(c, seat);
  const enemySeat = otherSeat(seat);
  const enemy = P(c, enemySeat);
  const attacker = p.board[a.from];
  if (!attacker) return fail("N\xE3o h\xE1 unidade nesse slot.");
  if ((t.attackCounts[a.from] ?? 0) >= getMaxAttacksPerTurn(attacker)) fail("Essa unidade j\xE1 atacou neste turno.");
  if (attacker.cardType === "Infantaria" && isBackline(a.from)) fail("Infantaria na Retaguarda n\xE3o pode atacar.");
  if (!enemy.board[a.to] || !getValidAttackTargets(a.from, p.board, enemy.board).has(a.to)) {
    fail("Alvo fora de alcance \u2014 tem uma carta bloqueando o caminho!");
  }
  c.ev.push({ t: "attack", seat, from: a.from, to: a.to });
  const options = hasEspiaoInVanguarda(p.board) ? [] : enemy.hand.filter((h) => h.cardType === "Emboscada").map((h) => h.id);
  if (options.length > 0) {
    c.s.pending = { kind: "ambush", seat: enemySeat, attacker: seat, from: a.from, to: a.to, options };
    log(c, enemySeat, `${attacker.name} est\xE1 atacando ${enemy.board[a.to].name} \u2014 ativar Emboscada?`);
    return;
  }
  resolveCombat(c, seat, a.from, a.to, null);
};
var respondAmbush = (c, seat, a) => {
  const pend = c.s.pending;
  if (!pend || pend.kind !== "ambush") return fail("N\xE3o h\xE1 nenhuma Emboscada a decidir.");
  if (pend.seat !== seat) return fail("Essa decis\xE3o n\xE3o \xE9 sua.");
  let chosen = null;
  if (a.cardId !== null) {
    if (!pend.options.includes(a.cardId)) fail("Essa Emboscada n\xE3o pode ser usada agora.");
    chosen = removeFromHand(c, seat, a.cardId);
    discard(c, seat, chosen);
    c.ev.push({ t: "ambush", seat, card: chosen });
    log(c, seat, `Emboscada ativada: ${chosen.name}!`);
  }
  c.s.pending = null;
  resolveCombat(c, pend.attacker, pend.from, pend.to, chosen);
};
var resolveAmbushEffect = (c, ambush, attackerBoard, attackerIndex, defenderBoard, defenderIndex) => {
  const unitSlots = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  if (ambush.name === "Bloqueio Instant\xE2neo") {
    const hasAlly = defenderIndex <= 9 && unitSlots.some((j) => areSlotsAdjacent(defenderIndex, j) && defenderBoard[j]);
    return { defenderIndex, cancelled: hasAlly };
  }
  if (ambush.name === "Contra-Manobra") {
    if (defenderIndex <= 9) {
      const partner = unitSlots.find((j) => areSlotsAdjacent(defenderIndex, j) && defenderBoard[j]);
      if (partner !== void 0) {
        [defenderBoard[defenderIndex], defenderBoard[partner]] = [defenderBoard[partner], defenderBoard[defenderIndex]];
        return { defenderIndex, cancelled: false };
      }
    }
    return { defenderIndex, cancelled: false };
  }
  if (ambush.name === "Forma\xE7\xE3o Quebrada") {
    const empty = unitSlots.filter((i) => i !== attackerIndex && !attackerBoard[i]);
    if (empty.length > 0) {
      const dest = pickRandom(c.s, empty);
      attackerBoard[dest] = attackerBoard[attackerIndex];
      attackerBoard[attackerIndex] = null;
    }
    return { defenderIndex, cancelled: true };
  }
  const buff = ambush.name === "Refor\xE7os Ocultos" ? { atk: 2, hp: 1 } : { atk: 2, hp: 2 };
  const defender = defenderBoard[defenderIndex];
  if (defender) defenderBoard[defenderIndex] = { ...defender, atk: defender.atk + buff.atk, hp: defender.hp + buff.hp };
  return { defenderIndex, cancelled: false };
};
var resolveCombat = (c, aSeat, from, to, ambush) => {
  const t = c.s.turn;
  const dSeat = otherSeat(aSeat);
  const aBoard = P(c, aSeat).board;
  const dBoard = P(c, dSeat).board;
  const attacker = aBoard[from];
  let target = to;
  let cancelled = false;
  if (ambush) {
    const r = resolveAmbushEffect(c, ambush, aBoard, from, dBoard, to);
    target = r.defenderIndex;
    cancelled = r.cancelled;
    if (cancelled) c.ev.push({ t: "cancelled", seat: aSeat, from, to });
  }
  t.attackCounts[from] = (t.attackCounts[from] ?? 0) + 1;
  if (cancelled) return;
  const defender = dBoard[target];
  const dead = [];
  let attackerAtk = getEffectiveAtk(attacker, from, aBoard, dBoard);
  if (attacker.name === "Fan\xE1tico da Cruzada" && dBoard[12] && dBoard[12].name !== "Cardeal Pedro, Voz da F\xE9") attackerAtk += 2;
  const defenderAtk = getEffectiveAtk(defender, target, dBoard, aBoard);
  const attackerReduction = getIncomingDamageReduction(from, aBoard);
  const defenderReduction = getIncomingDamageReduction(target, dBoard);
  const attackerHpBonus = (attacker.pendingCombatBonus?.hp ?? 0) + getAuraCombatHpBonus(attacker, aBoard);
  const defenderHpBonus = (defender.pendingCombatBonus?.hp ?? 0) + getAuraCombatHpBonus(defender, dBoard);
  const damageToDefender = Math.max(0, attackerAtk - defenderReduction);
  const damageToAttacker = Math.max(0, defenderAtk - attackerReduction);
  const defSoak = soak(c, dSeat, target, defender, damageToDefender);
  const atkSoak = soak(c, aSeat, from, attacker, damageToAttacker);
  const throughToDefender = defSoak.through, throughToAttacker = atkSoak.through;
  if (target === 12 && throughToDefender > 0 && hasEspiaoOnBoard(dBoard)) {
    P(c, dSeat).pendingGeneralBlock = true;
    log(c, dSeat, "Infiltrado da Ordem: a habilidade do General foi bloqueada no pr\xF3ximo turno!");
  }
  const newAttacker = { ...atkSoak.card, hp: attacker.hp - Math.max(0, throughToAttacker - attackerHpBonus), pendingCombatBonus: void 0 };
  const newDefender = { ...defSoak.card, hp: defender.hp - Math.max(0, throughToDefender - defenderHpBonus), pendingCombatBonus: void 0 };
  c.ev.push({ t: "damage", seat: aSeat, slot: from, amount: throughToAttacker });
  c.ev.push({ t: "damage", seat: dSeat, slot: target, amount: throughToDefender });
  if (newAttacker.hp <= 0) {
    aBoard[from] = null;
    dead.push({ seat: aSeat, slot: from, card: newAttacker });
  } else {
    aBoard[from] = newAttacker;
    if (attacker.name === "Batedor") t.batedorFree = from;
  }
  if (newDefender.hp <= 0) {
    dBoard[target] = null;
    dead.push({ seat: dSeat, slot: target, card: newDefender });
  } else dBoard[target] = newDefender;
  if (attacker.name === "Jorge, Lan\xE7a Sagrada" && isFrontline(target) && dBoard[target + 5]) {
    const d = damageSlot(c, dSeat, target + 5, 2);
    if (d) dead.push({ seat: dSeat, ...d });
  }
  [aSeat, dSeat].forEach((seat) => sendDestroyed(c, seat, dead.filter((d) => d.seat === seat)));
};
var move = (c, seat, a) => {
  assertCanAct(c, seat);
  const t = c.s.turn;
  const free = t.batedorFree !== null && t.phase === "combate";
  if (!(t.phase === "movimentacao" || free)) fail("S\xF3 d\xE1 pra reposicionar na fase de Movimenta\xE7\xE3o!");
  if (a.from > 9 || a.to > 9 || a.from < 0 || a.to < 0) fail("Essa carta n\xE3o pode ser reposicionada.");
  const board = P(c, seat).board;
  const mover = board[a.from];
  if (!mover) return fail("N\xE3o h\xE1 unidade nesse slot.");
  if (free) {
    if (a.from !== t.batedorFree) fail("S\xF3 d\xE1 pra mover o Batedor que acabou de atacar.");
  } else if (t.moved.includes(a.from) && t.bonusRepositions <= 0) {
    fail("Essa unidade j\xE1 se reposicionou nesse turno.");
  }
  if (!canReposition(mover, a.from, a.to)) fail("S\xF3 d\xE1 pra reposicionar para um slot adjacente!");
  const wasAlreadyMoved = t.moved.includes(a.from);
  const occupant = board[a.to];
  board[a.from] = occupant;
  board[a.to] = mover;
  c.ev.push({ t: "move", seat, from: a.from, to: a.to, swapped: !!occupant });
  applyFormationCaptainBuff(c, seat, a.to);
  if (free) {
    t.batedorFree = null;
    log(c, seat, "Batedor se reposicionou ap\xF3s o combate!");
    return;
  }
  [a.from, a.to].forEach((i) => {
    if (!t.moved.includes(i)) t.moved.push(i);
  });
  if (wasAlreadyMoved) t.bonusRepositions = Math.max(0, t.bonusRepositions - 1);
};
var advance = (c, seat) => {
  assertCanAct(c, seat);
  const t = c.s.turn;
  const phases = activePhases(c.s);
  const i = phases.indexOf(t.phase);
  if (i < phases.length - 1) {
    t.phase = phases[i + 1];
    t.batedorFree = null;
    c.ev.push({ t: "phase", seat, phase: t.phase });
    return;
  }
  const excess = P(c, seat).hand.length - HAND_LIMIT;
  if (excess > 0) {
    c.s.pending = { kind: "discard", seat, count: excess };
    log(c, seat, `Voc\xEA tem ${P(c, seat).hand.length} cartas: descarte ${excess} para terminar o turno.`);
    return;
  }
  endTurn(c);
};
var discardExcess = (c, seat, a) => {
  assertCanAct(c, seat, true);
  const pend = c.s.pending;
  if (!pend || pend.kind !== "discard") return fail("N\xE3o h\xE1 descarte pendente.");
  if (pend.seat !== seat) return fail("Esse descarte n\xE3o \xE9 seu.");
  const ids = a.cardIds;
  if (new Set(ids).size !== ids.length) fail("Escolha cartas diferentes.");
  if (ids.length !== pend.count) fail(`Descarte exatamente ${pend.count} carta(s).`);
  const hand = P(c, seat).hand;
  if (!ids.every((id) => hand.some((h) => h.id === id))) fail("Essa carta n\xE3o est\xE1 na sua m\xE3o.");
  ids.forEach((id) => discard(c, seat, removeFromHand(c, seat, id)));
  c.s.pending = null;
  log(c, seat, `${ids.length} carta(s) descartada(s).`);
  endTurn(c);
};
var clone = (x) => JSON.parse(JSON.stringify(x));
var applyAction = (state, seat, action) => {
  const c = { s: clone(state), ev: [] };
  try {
    switch (action.type) {
      case "begin":
        if (c.s.turn.started) fail("A partida j\xE1 come\xE7ou.");
        c.s.turn.started = true;
        startTurn(c, c.s.turn.first);
        break;
      case "play":
        playCard(c, seat, action);
        break;
      case "attack":
        attack(c, seat, action);
        break;
      case "move":
        move(c, seat, action);
        break;
      case "ability":
        useAbility(c, seat, action);
        break;
      case "ambush":
        respondAmbush(c, seat, action);
        break;
      case "choose":
        choose(c, seat, action);
        break;
      case "discard":
        discardExcess(c, seat, action);
        break;
      case "advance":
        advance(c, seat);
        break;
      case "concede":
        if (c.s.winner !== null) fail("A partida j\xE1 terminou.");
        setWinner(c, otherSeat(seat));
        break;
      default:
        fail("A\xE7\xE3o desconhecida.");
    }
  } catch (e) {
    if (e instanceof RuleError) return { ok: false, error: e.message };
    throw e;
  }
  return { ok: true, state: c.s, events: c.ev };
};

// src/engine/ai.ts
var randomOf = (rand, items) => items[Math.floor(rand() * items.length)];
var weakest = (board, slots) => slots.reduce((a, b) => board[a].hp <= board[b].hp ? a : b);
var UNIT_SLOTS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
var isSoldier = (c) => SOLDIER_TYPES.includes(c.cardType);
var cardValue = (c) => {
  if (isSoldier(c)) return c.atk * 1.2 + c.hp + c.cost * 0.2;
  if (c.cardType === "Rel\xEDquia" || c.cardType === "Terreno") return 6;
  if (c.cardType === "Emboscada") return 3.5;
  if (c.cardType === "T\xE1tica") return 3 + c.cost * 0.5;
  return 1;
};
var unitWorth = (c) => c.atk * 1.2 + c.hp;
var isRangedType = (c) => c.cardType === "Arqueiro" || c.cardType === "Artilharia";
var boardScore = (me, foe) => {
  let score = 0;
  const foeThreat = UNIT_SLOTS.some((i) => foe[i] && foe[i].atk > 0);
  for (const i of UNIT_SLOTS) {
    const u = me[i];
    if (!u) continue;
    const front = i <= 4;
    const worth = u.atk * 1.2 + u.hp;
    if (u.atk > 0) {
      if (u.cardType === "Infantaria") score += front ? 2.5 : -2.5;
      else if (isRangedType(u)) score += front ? -1 : 1.2;
      else score += front ? 0.8 : 0.2;
    } else if (front) {
      score += u.hp >= 3 ? 0.8 : 0.2;
    }
    if (front) score += u.hp >= 4 ? 1.2 : u.hp <= 2 ? -1.2 : 0;
    else if (u.hp <= 2) score += 0.6;
    if (!front && !me[i - 5] && foeThreat) score -= 0.12 * worth;
    const facing = front ? foe[i] : null;
    if (facing) {
      if (u.hp > facing.atk && u.atk >= facing.hp) score += 1;
      else if (u.hp <= facing.atk && u.atk < facing.hp) score -= 1;
    }
  }
  if (foeThreat) {
    if (!me[2] && !me[7]) score -= 7;
    if (me[10] && !me[1] && !me[6]) score -= 1.5;
    if (me[11] && !me[3] && !me[8]) score -= 1.5;
  }
  return score;
};
var swapped = (board, a, b) => {
  const next = [...board];
  [next[a], next[b]] = [next[b], next[a]];
  return next;
};
var moveOptions = (s, seat, only) => {
  const me = s.players[seat].board;
  const foe = s.players[otherSeat(seat)].board;
  const t = s.turn;
  const free = only !== void 0;
  const base = boardScore(me, foe);
  const aurelion = me[12]?.name === "Comandante Aurelion, Mestre da Forma\xE7\xE3o" && t.moved.length < 2;
  const out = [];
  for (const from of UNIT_SLOTS) {
    const u = me[from];
    if (!u || free && from !== only) continue;
    if (!free && t.moved.includes(from) && t.bonusRepositions <= 0) continue;
    for (const to of UNIT_SLOTS) {
      if (!canReposition(u, from, to)) continue;
      const after = swapped(me, from, to);
      let delta = boardScore(after, foe) - base;
      if (u.name === "Capit\xE3o de Forma\xE7\xE3o") delta += 0.5 * adjacentSlots(to).filter((j) => after[j]).length;
      if (aurelion && !free) delta += 0.6;
      out.push({ from, to, delta });
    }
  }
  return out;
};
var bestMove = (s, seat, threshold, only) => {
  const options = moveOptions(s, seat, only).filter((o) => o.delta >= threshold);
  return options.length ? options.reduce((a, b) => b.delta > a.delta ? b : a) : null;
};
var planGain = (s, seat, bonus) => {
  let me = [...s.players[seat].board];
  const foe = s.players[otherSeat(seat)].board;
  const moved = /* @__PURE__ */ new Set();
  let gain = 0;
  let extra = bonus;
  for (let step = 0; step < 12; step++) {
    const base = boardScore(me, foe);
    let best = null;
    for (const from of UNIT_SLOTS) {
      const u = me[from];
      if (!u || moved.has(from) && extra <= 0) continue;
      for (const to of UNIT_SLOTS) {
        if (!canReposition(u, from, to)) continue;
        const delta = boardScore(swapped(me, from, to), foe) - base;
        if (delta >= 0.75 && (!best || delta > best.delta)) best = { from, to, delta };
      }
    }
    if (!best) break;
    if (moved.has(best.from)) extra -= 1;
    me = swapped(me, best.from, best.to);
    moved.add(best.from);
    moved.add(best.to);
    gain += best.delta;
  }
  return gain;
};
var bestSlot = (s, seat, card, empty, rand) => {
  const me = s.players[seat].board;
  const foe = s.players[otherSeat(seat)].board;
  let best = empty[0];
  let bestScore = -Infinity;
  for (const slot of empty) {
    const next = [...me];
    next[slot] = card;
    const score = boardScore(next, foe) + rand() * 0.01;
    if (score > bestScore) {
      bestScore = score;
      best = slot;
    }
  }
  return best;
};
var attackScore = (me, foe, from, to) => {
  const a = me[from];
  const d = foe[to];
  const raw = Math.max(0, getEffectiveAtk(a, from, me, foe) - getIncomingDamageReduction(to, foe));
  const rawBack = Math.max(0, getEffectiveAtk(d, to, foe, me) - getIncomingDamageReduction(from, me));
  const soak2 = (card, dmgIn) => card.block ? 0 : Math.max(0, dmgIn - (card.shield ?? 0));
  const dmg = soak2(d, raw), back = soak2(a, rawBack);
  const kills = dmg >= d.hp;
  const dies = back >= a.hp;
  let score = kills ? d.atk * 1.2 + d.hp + 2 : dmg * 0.6;
  score -= dies ? a.atk * 1.2 + a.hp : back * 0.4;
  if (to === 12) score += dmg * 1.5 + (kills ? 100 : 0);
  else if (to === 10 || to === 11) score += kills ? 1 : 0.3;
  return score;
};
var tacticPlay = (s, seat, card, rand) => {
  const me = s.players[seat];
  const foe = s.players[otherSeat(seat)];
  const play = (target) => ({ type: "play", cardId: card.id, target });
  const enemyUnits = UNIT_SLOTS.filter((i) => foe.board[i]);
  const ownUnits = UNIT_SLOTS.filter((i) => me.board[i]);
  switch (card.name) {
    case "Tributo de Guerra":
      return play();
    case "Trabuco de Cerco": {
      const hit = [...enemyUnits, 12].filter((i) => foe.board[i]);
      const kills = hit.filter((i) => foe.board[i].hp <= 2).length;
      return kills >= 1 && hit.length >= 3 || kills >= 2 || hit.length >= 5 ? play() : null;
    }
    case "Balestra de Precis\xE3o": {
      const killable = enemyUnits.filter((i) => foe.board[i].hp <= 3);
      if (killable.length === 0) return null;
      return play(killable.reduce((a, b) => unitWorth(foe.board[a]) >= unitWorth(foe.board[b]) ? a : b));
    }
    case "Catapulta de Guerra": {
      const rows = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]].map((row) => {
        const units = row.filter((i) => foe.board[i]);
        return { slot: row[0], count: units.length, kills: units.filter((i) => foe.board[i].hp <= 2).length };
      });
      const best = rows.reduce((a, b) => b.kills * 2 + b.count > a.kills * 2 + a.count ? b : a);
      return best.kills >= 1 && best.count >= 2 || best.count >= 3 ? play(best.slot) : null;
    }
    case "Linha Fechada": {
      const scored = ownUnits.map((i) => ({ i, n: adjacentSlots(i).filter((j) => me.board[j]).length })).filter((x) => x.n >= 2);
      return scored.length ? play(scored.reduce((a, b) => b.n > a.n ? b : a).i) : null;
    }
    case "Ordem de Retirada": {
      const hurt = [0, 1, 2, 3, 4].filter((i) => me.board[i] && !me.board[i + 5] && isCardDamaged(me.board[i]));
      return hurt.length ? play(weakest(me.board, hurt)) : null;
    }
    case "Reformar Linhas":
      return planGain(s, seat, 3) - planGain(s, seat, 0) >= 1.5 ? play() : null;
    case "Avan\xE7o Coordenado": {
      if (s.turn.phase !== "movimentacao") return null;
      const movers = s.turn.moved.filter((i) => me.board[i] && i <= 9 && me.board[i].atk > 0);
      return movers.length ? play(movers.reduce((a, b) => me.board[b].atk > me.board[a].atk ? b : a)) : null;
    }
    case "Reposicionamento R\xE1pido": {
      if (!combatOpen(s) || !foe.board[12]) return null;
      const blockers = [2, 7].filter((i) => foe.board[i]);
      if (blockers.length !== 1) return null;
      const hitters = ownUnits.filter((i) => {
        const u = me.board[i];
        if (u.atk < 2 || u.cardType === "Infantaria" && i > 4) return false;
        return isRangedType(u) || Math.abs(getLaneCol(i) - 2) <= 1;
      });
      const free = adjacentSlots(blockers[0]).filter((j) => !foe.board[j]);
      const opens = free.filter((j) => j !== 2 && j !== 7);
      return hitters.length > 0 && free.length > 0 && opens.length / free.length >= 0.6 ? play(blockers[0]) : null;
    }
    case "Armadura de Guerra":
    case "Coura\xE7a Refor\xE7ada":
    case "Flechas Venenosas":
    case "Espada Longa": {
      const kind = TARGETABLE_TACTICS[card.name];
      const allowed = EQUIP_ALLOWED_TYPES[kind];
      const targets = ownUnits.filter((i) => allowed.includes(me.board[i].cardType) && i <= 4);
      if (targets.length === 0) return null;
      return play(targets.reduce((a, b) => unitWorth(me.board[b]) > unitWorth(me.board[a]) ? b : a));
    }
    case "Retorno do Soldado":
      return me.graveyard.some(isSoldier) ? play() : null;
    case "Graal da D\xE1diva":
      return me.deckList.some((n) => {
        const t = getCardDef(n)?.cardType;
        return t === "Terreno" || t === "Rel\xEDquia";
      }) && me.hand.length <= 9 ? play() : null;
    case "Doutrina Renovada":
      return me.hand.length <= 8 && me.deckList.some((n) => getCardDef(n)?.cardType === "T\xE1tica") ? play() : null;
    case "Recrutamento Seletivo":
    case "Recrutar Veteranos":
      return me.hand.length <= 8 ? play() : null;
    case "Chamado \xE0s Armas": {
      const free = [0, 1, 2, 3, 4].filter((i) => !me.board[i]).length;
      const has = me.deckList.some((n) => {
        const d = getCardDef(n);
        return isSoldier(d) && d.atk === 0;
      });
      return free >= 1 && has ? play() : null;
    }
    default:
      void rand;
      return null;
  }
};
var bestIds = (cards, n) => [...cards].sort((a, b) => cardValue(b) - cardValue(a)).slice(0, n).map((c) => c.id);
var aiNextAction = (state, seat, rand = Math.random) => {
  const me = state.players[seat];
  const foe = state.players[otherSeat(seat)];
  const t = state.turn;
  const pend = state.pending;
  if (pend && pend.seat === seat) {
    if (pend.kind === "ambush") {
      const attacker = state.players[pend.attacker].board[pend.from];
      const defender = me.board[pend.to];
      const options = me.hand.filter((h) => pend.options.includes(h.id));
      if (attacker && defender && options.length > 0 && defender.hp - attacker.atk <= 0) return { type: "ambush", cardId: options[0].id };
      return { type: "ambush", cardId: null };
    }
    if (pend.kind === "discard") {
      const worst = [...me.hand].sort((a, b) => cardValue(a) - cardValue(b)).slice(0, pend.count).map((c) => c.id);
      return { type: "discard", cardIds: worst };
    }
    return { type: "choose", cardIds: bestIds(pend.options, Math.max(pend.min, Math.min(pend.max, pend.options.length))) };
  }
  if (t.phase === "preparacao" || t.phase === "pos_combate") {
    const afterCombat = t.phase === "pos_combate";
    const general = me.board[12];
    if (general?.name === "Cardeal Pedro, Voz da F\xE9" && me.generalAbilityUses < 1 && !me.generalAbilityBlocked && me.gold >= 2) {
      const allies = UNIT_SLOTS.filter((i) => me.board[i]);
      if (allies.length > 0) return { type: "ability", slot: 12, target: weakest(me.board, allies) };
    }
    for (const i of UNIT_SLOTS) {
      const card = me.board[i];
      if (!card || t.activated.includes(card.id)) continue;
      if (card.name === "Mercador da Cruzada") return { type: "ability", slot: i };
      if (card.name === "Cavaleiro Hospital\xE1rio") {
        const damaged = UNIT_SLOTS.filter((j) => me.board[j] && isCardDamaged(me.board[j]));
        const enemyFront = [0, 1, 2, 3, 4].filter((j) => foe.board[j]);
        if (damaged.length === 0 && enemyFront.length === 0) continue;
        return {
          type: "ability",
          slot: i,
          target: damaged.length > 0 ? weakest(me.board, damaged) : void 0,
          target2: enemyFront.length > 0 ? randomOf(rand, enemyFront) : void 0
        };
      }
    }
    const afford = (c) => c.cost <= me.gold;
    for (const card of me.hand) if (card.name === "Tributo de Guerra") {
      const a = tacticPlay(state, seat, card, rand);
      if (a) return a;
    }
    for (const card of me.hand) {
      if (!afford(card) || card.cardType !== "T\xE1tica") continue;
      if (!["Balestra de Precis\xE3o", "Trabuco de Cerco", "Catapulta de Guerra"].includes(card.name)) continue;
      const a = tacticPlay(state, seat, card, rand);
      if (a) return a;
    }
    for (const card of me.hand) {
      if (!afford(card)) continue;
      if (card.cardType === "Rel\xEDquia" && !me.board[10]) return { type: "play", cardId: card.id, slot: 10 };
      if (card.cardType === "Terreno" && !me.board[11]) return { type: "play", cardId: card.id, slot: 11 };
    }
    for (const card of afterCombat ? [] : me.hand) {
      if (!isSoldier(card) || !afford(card)) continue;
      const empty = UNIT_SLOTS.filter((i) => !me.board[i]);
      if (empty.length === 0) break;
      return { type: "play", cardId: card.id, slot: bestSlot(state, seat, card, empty, rand) };
    }
    for (const card of me.hand) {
      if (card.cardType !== "T\xE1tica" || !afford(card)) continue;
      if (["Balestra de Precis\xE3o", "Trabuco de Cerco", "Catapulta de Guerra", "Tributo de Guerra"].includes(card.name)) continue;
      const a = tacticPlay(state, seat, card, rand);
      if (a) return a;
    }
    return { type: "advance" };
  }
  if (t.phase === "combate") {
    if (t.batedorFree !== null) {
      const m2 = bestMove(state, seat, 0.4, t.batedorFree);
      if (m2) return { type: "move", from: m2.from, to: m2.to };
    }
    let best = null;
    for (const i of UNIT_SLOTS) {
      const attacker = me.board[i];
      if (!attacker || attacker.atk <= 0) continue;
      if ((t.attackCounts[i] ?? 0) >= getMaxAttacksPerTurn(attacker)) continue;
      for (const to of getValidAttackTargets(i, me.board, foe.board)) {
        const score = attackScore(me.board, foe.board, i, to);
        if (!best || score > best.score) best = { from: i, to, score };
      }
    }
    if (best && best.score >= -1.5) return { type: "attack", from: best.from, to: best.to };
    return { type: "advance" };
  }
  const m = bestMove(state, seat, 0.75);
  if (m) return { type: "move", from: m.from, to: m.to };
  for (const card of me.hand) {
    if (card.name !== "Avan\xE7o Coordenado" || card.cost > me.gold) continue;
    const a = tacticPlay(state, seat, card, rand);
    if (a) return a;
  }
  return { type: "advance" };
};

// src/engine/deck.ts
var DECK_MIN_CARDS = 40;
var DECK_MAX_CARDS = 60;
var DECK_MAX_COPIES = 4;
var deckCardCount = (cards) => Object.values(cards).reduce((sum, n) => sum + n, 0);
var deckProblem = (cards, general, collection) => {
  if (!isGeneralName(general)) return "General inv\xE1lido.";
  const n = deckCardCount(cards);
  if (n < DECK_MIN_CARDS) return `Faltam ${DECK_MIN_CARDS - n} cartas (m\xEDnimo ${DECK_MIN_CARDS})`;
  if (n > DECK_MAX_CARDS) return `${n - DECK_MAX_CARDS} cartas a mais (m\xE1ximo ${DECK_MAX_CARDS})`;
  for (const [name, copies] of Object.entries(cards)) {
    const def = getCardDef(name);
    if (!def || def.cardType === "General") return `Carta inv\xE1lida no deck: ${name}`;
    if (!Number.isInteger(copies) || copies < 1) return `Quantidade inv\xE1lida de ${name}`;
    if (copies > DECK_MAX_COPIES) return `Limite de ${DECK_MAX_COPIES} c\xF3pias por carta (${name})`;
    if (collection && copies > (collection[name] ?? 0)) return `Voc\xEA n\xE3o tem ${copies} c\xF3pias de ${name}`;
  }
  if (collection && (collection[general] ?? 0) < 1) return `Voc\xEA n\xE3o tem o General ${general}`;
  return null;
};

// src/engine/rewards.ts
var REWARD_MIN_ROUNDS = 3;
var REWARD_MIN_STEPS = 14;
var rewardFor = (r) => {
  if (r.rounds < REWARD_MIN_ROUNDS || r.steps < REWARD_MIN_STEPS) return { xp: 0, coroas: 0, reason: "too_short" };
  if (r.won) return r.vsBot ? { xp: 35, coroas: 12, reason: "win" } : { xp: 60, coroas: 25, reason: "win" };
  if (r.ending !== "general") return { xp: 0, coroas: 0, reason: "abandoned" };
  return r.vsBot ? { xp: 12, coroas: 4, reason: "loss" } : { xp: 25, coroas: 8, reason: "loss" };
};
var xpToNext = (level) => 100 + 50 * (Math.max(1, level) - 1);
var applyReward = (p, gain) => {
  let { level, xp } = p;
  xp += gain.xp;
  let levelsGained = 0;
  while (xp >= xpToNext(level) && level < 99) {
    xp -= xpToNext(level);
    level += 1;
    levelsGained += 1;
  }
  return { level, xp, coroas: p.coroas + gain.coroas, levelsGained };
};

// src/engine/view.ts
var hiddenCard = (id) => ({ id, name: "", cardType: "T\xE1tica", atk: 0, hp: 0, cost: 0, effect: "", hidden: true });
var redactPlayer = (p) => ({
  ...p,
  hand: p.hand.map((c) => hiddenCard(c.id)),
  // Nothing about the deck's contents or order is revealed; only how many cards remain in the queue.
  deckList: [],
  drawPile: p.drawPile.map(() => "")
});
var redactFor = (state, seat) => {
  const other = seat === 0 ? 1 : 0;
  const players = [state.players[0], state.players[1]];
  players[other] = redactPlayer(players[other]);
  players[seat] = { ...players[seat], drawPile: players[seat].drawPile.map(() => "") };
  let pending = state.pending;
  if (pending && pending.kind === "pick" && pending.seat !== seat) pending = { ...pending, options: pending.options.map((o) => hiddenCard(o.id)) };
  if (pending && pending.kind === "ambush" && pending.seat !== seat) pending = { ...pending, options: [] };
  return { ...state, rng: 0, players, pending };
};
var redactEvents = (events, seat) => events.filter((e) => !(e.t === "log" && e.private && e.seat !== seat)).map((e) => {
  if (e.t === "draw" && e.seat !== seat) return { ...e, card: hiddenCard(e.card.id) };
  return e;
});
var mirrorSeats = (state) => {
  const flip = (s) => s === 0 ? 1 : 0;
  const pending = state.pending ? state.pending.kind === "ambush" ? { ...state.pending, seat: flip(state.pending.seat), attacker: flip(state.pending.attacker) } : { ...state.pending, seat: flip(state.pending.seat) } : null;
  return {
    ...state,
    players: [state.players[1], state.players[0]],
    turn: { ...state.turn, active: flip(state.turn.active), first: flip(state.turn.first) },
    pending,
    winner: state.winner === null ? null : flip(state.winner)
  };
};
var mirrorEvents = (events) => events.map((e) => "seat" in e ? { ...e, seat: e.seat === 0 ? 1 : 0 } : e);
var viewFor = (state, seat) => seat === 1 ? mirrorSeats(redactFor(state, seat)) : redactFor(state, seat);
var eventsFor = (events, seat) => seat === 1 ? mirrorEvents(redactEvents(events, seat)) : redactEvents(events, seat);

// server/handler.ts
var defaultConfig = () => ({ botAfterMs: 15e3, turnMs: 15e4, promptMs: 6e4, maxTimeouts: 2, now: () => Date.now(), random: Math.random });
var BOT_PROFILE = { name: "Advers\xE1rio", avatarId: "batedora" };
var STALE_MATCH_MS = 45 * 60 * 1e3;
var BOT_STEP_LIMIT = 600;
var AUTO_STEP_LIMIT = 40;
var recipeDeck = (id) => ({ general: DECK_RECIPES[id].general, cards: { ...DECK_RECIPES[id].cards } });
var botDeckFor = (deck) => deck.general === DECK_RECIPES.capitao.general ? recipeDeck("cardeal") : recipeDeck("capitao");
var playerOf = (m, userId) => m.seat0 === userId ? 0 : m.seat1 === userId ? 1 : null;
var userOfSeat = (m, seat) => seat === 0 ? m.seat0 : m.seat1;
var moverOf = (s) => s.pending ? s.pending.seat : s.turn.active;
var moverKey = (s) => `${s.turn.round}:${s.turn.active}:${s.pending ? s.pending.kind + s.pending.seat : ""}`;
var startWork = (m) => ({ state: m.state, n: m.steps_count, key: moverKey(m.state), deadline: m.turn_deadline, steps: [], views: [] });
var applyStep = (m, w, seat, action, cfg, notes) => {
  const r = applyAction(w.state, seat, action);
  if (r.ok === false) return r;
  w.state = r.state;
  const n = ++w.n;
  w.steps.push({ n, seat, action });
  const key = moverKey(w.state);
  if (w.state.winner !== null) w.deadline = null;
  else if (key !== w.key) {
    w.key = key;
    w.deadline = cfg.now() + (w.state.pending ? cfg.promptMs : cfg.turnMs);
  }
  [0, 1].forEach((viewer) => {
    const user = userOfSeat(m, viewer);
    if (!user) return;
    w.views.push({
      n,
      viewer,
      user,
      actor: seat === viewer ? 0 : 1,
      action,
      events: eventsFor([...r.events, ...notes ? notes(viewer) : []], viewer),
      state: viewFor(w.state, viewer),
      deadline: w.deadline
    });
  });
  return { ok: true };
};
var runBot = (m, w, cfg) => {
  if (m.bot_seat === null) return;
  const bot = m.bot_seat;
  const rng = { rng: seedFrom(m.seed * 31 + w.n) };
  const rand = () => nextRandom(rng);
  for (let i = 0; i < BOT_STEP_LIMIT && w.state.winner === null; i++) {
    if (moverOf(w.state) !== bot) break;
    if (applyStep(m, w, bot, aiNextAction(w.state, bot, rand), cfg).ok === false) break;
  }
};
var patchOf = (m, w, extra = {}) => ({
  state: w.state,
  steps_count: w.n,
  status: w.state.winner !== null ? "finished" : "active",
  winner: w.state.winner,
  turn_deadline: w.deadline,
  timeouts: m.timeouts,
  end_reason: m.end_reason,
  ...extra
});
var ensureRewards = async (db, m) => {
  if (m.status !== "finished" || m.winner === null) return null;
  if (m.rewards) return m.rewards;
  const rows = [];
  for (const seat of [0, 1]) {
    const user = userOfSeat(m, seat);
    if (!user) continue;
    const prof = await db.profile(user);
    if (!prof) continue;
    const won = m.winner === seat;
    const reward = rewardFor({ won, vsBot: m.bot_seat !== null, ending: won ? "general" : m.end_reason ?? "general", rounds: m.state.turn.round, steps: m.steps_count });
    const after = applyReward({ level: prof.level, xp: prof.xp, coroas: prof.coroas }, reward);
    rows.push({ user_id: user, seat, reason: reward.reason, xp: reward.xp, coroas: reward.coroas, level: after.level, xp_after: after.xp, coroas_after: after.coroas, levels_gained: after.levelsGained });
  }
  if (rows.length === 0) return null;
  const applied = await db.applyRewards(m.id, rows);
  if (applied) return rows;
  return (await db.getMatch(m.id))?.rewards ?? null;
};
var rewardOf = (m, rows, userId) => rows?.find((r) => r.user_id === userId) ?? m.rewards?.find((r) => r.user_id === userId) ?? null;
var enforceClock = async (db, m, cfg) => {
  for (let guard = 0; guard < 3; guard++) {
    if (m.status !== "active" || m.turn_deadline === null || cfg.now() <= m.turn_deadline) return m;
    const mover = moverOf(m.state);
    if (mover === m.bot_seat) return m;
    const timeouts = [m.timeouts[0], m.timeouts[1]];
    timeouts[mover] += 1;
    const w = startWork(m);
    let endReason = m.end_reason;
    if (timeouts[mover] >= cfg.maxTimeouts) {
      endReason = "timeout";
      applyStep(m, w, mover, { type: "concede" }, cfg, (viewer) => [{ t: "log", seat: viewer, text: viewer === mover ? "O tempo acabou de novo: voc\xEA perdeu a partida." : "O advers\xE1rio esgotou o tempo: vit\xF3ria!" }]);
    } else {
      let first = true;
      for (let i = 0; i < AUTO_STEP_LIMIT && w.state.winner === null && moverOf(w.state) === mover; i++) {
        const action = w.state.pending ? aiNextAction(w.state, mover, () => 0.5) : { type: "advance" };
        const note = first ? (viewer) => [{ t: "log", seat: viewer, text: viewer === mover ? "O tempo acabou: seu turno foi encerrado automaticamente." : "O advers\xE1rio demorou demais: turno encerrado automaticamente." }] : void 0;
        if (applyStep(m, w, mover, action, cfg, note).ok === false) break;
        first = false;
      }
      runBot(m, w, cfg);
      if (w.state.winner === null && w.key === moverKey(m.state)) w.deadline = cfg.now() + cfg.turnMs;
    }
    const saved = await db.saveMatch(m.id, m.steps_count, patchOf({ ...m, timeouts, end_reason: endReason }, w, { timeouts, end_reason: endReason }), w.steps, w.views);
    const fresh = await db.getMatch(m.id);
    if (!fresh) return m;
    m = fresh;
    if (!saved) continue;
    if (m.status === "finished") await ensureRewards(db, m);
  }
  return m;
};
var viewRowsOf = (db, m, seat, since) => db.views(m.id, seat, since);
var initOf = async (db, m, userId, cfg) => {
  const seat = playerOf(m, userId);
  const oppId = userOfSeat(m, otherSeat(seat));
  const prof = oppId ? await db.profile(oppId) : null;
  const rows = await viewRowsOf(db, m, seat, 0);
  const resumed = rows.some((r) => r.actor === 0 && r.action.type !== "begin") || cfg.now() - Date.parse(m.created_at) > 6e4;
  const start = viewFor(createMatch({ seed: m.seed, decks: m.decks, first: m.first }).state, seat);
  return {
    id: m.id,
    iGoFirst: m.first === seat,
    mySide: seat === 0 ? "cara" : "coroa",
    myDeck: m.decks[seat],
    opponentGeneral: m.decks[otherSeat(seat)].general,
    opponent: oppId ? { name: prof?.username ?? "Jogador", avatarId: prof?.avatar_id ?? "batedora", bot: false } : { ...BOT_PROFILE, bot: true },
    start,
    rows: resumed ? [] : rows,
    latest: resumed ? rows[rows.length - 1] ?? null : null,
    status: m.status,
    winner: m.winner === null ? null : m.winner === seat ? 0 : 1,
    resumed,
    deadline: m.turn_deadline,
    now: cfg.now()
  };
};
var startMatch = async (db, cfg, a, b) => {
  const seed = Math.floor(cfg.random() * 2147483647) + 1;
  const first = cfg.random() < 0.5 ? 0 : 1;
  const [p0, p1] = cfg.random() < 0.5 ? [b, a] : [a, b];
  const bot_seat = p0.user === null ? 0 : p1.user === null ? 1 : null;
  const decks = [p0.deck, p1.deck];
  const created = createMatch({ seed, decks, first });
  const draft = {
    seed,
    status: "active",
    first,
    seat0: p0.user,
    seat1: p1.user,
    bot_seat,
    decks,
    state: created.state,
    steps_count: 0,
    winner: null,
    turn_deadline: null,
    timeouts: [0, 0],
    end_reason: null,
    rewards: null
  };
  const m = { ...draft, id: "", created_at: new Date(cfg.now()).toISOString() };
  const w = startWork(m);
  w.key = "";
  if (applyStep(m, w, first, { type: "begin" }, cfg).ok === false) throw new Error("begin refused");
  runBot(m, w, cfg);
  return db.createMatch({ ...draft, ...patchOf(m, w) }, w.steps, w.views);
};
var finishIfStale = async (db, cfg, m) => {
  if (!m) return null;
  if (cfg.now() - Date.parse(m.created_at) > STALE_MATCH_MS) {
    await db.saveMatch(m.id, m.steps_count, { ...patchOf(m, startWork(m)), status: "finished" }, [], []);
    return null;
  }
  return m;
};
var handleGame = async (db, userId, req, cfg = defaultConfig()) => {
  switch (req.op) {
    case "queue": {
      if (!req.cards || typeof req.cards !== "object" || typeof req.general !== "string") return { ok: false, error: "Deck inv\xE1lido." };
      const resume = await finishIfStale(db, cfg, await db.activeMatchOf(userId));
      if (resume) return { ok: true, status: "matched", match: await initOf(db, await enforceClock(db, resume, cfg), userId, cfg) };
      const problem = deckProblem(req.cards, req.general, await db.collection(userId));
      if (problem) return { ok: false, error: problem };
      const deck = { general: req.general, cards: req.cards };
      await db.queueDelete(userId);
      if (req.vsBot) {
        const m = await startMatch(db, cfg, { user: userId, deck }, { user: null, deck: botDeckFor(deck) });
        return { ok: true, status: "matched", match: await initOf(db, m, userId, cfg) };
      }
      const other = await db.queueTake(userId);
      if (other) {
        const m = await startMatch(db, cfg, { user: userId, deck }, { user: other.user_id, deck: other.deck });
        return { ok: true, status: "matched", match: await initOf(db, m, userId, cfg) };
      }
      await db.queuePut({ user_id: userId, deck, created_at: new Date(cfg.now()).toISOString() });
      return { ok: true, status: "waiting" };
    }
    case "status": {
      const active = await finishIfStale(db, cfg, await db.activeMatchOf(userId));
      if (active) return { ok: true, status: "matched", match: await initOf(db, await enforceClock(db, active, cfg), userId, cfg) };
      const q = await db.queueGet(userId);
      if (!q) return { ok: true, status: "none" };
      if (cfg.now() - Date.parse(q.created_at) >= cfg.botAfterMs) {
        await db.queueDelete(userId);
        const m = await startMatch(db, cfg, { user: userId, deck: q.deck }, { user: null, deck: botDeckFor(q.deck) });
        return { ok: true, status: "matched", match: await initOf(db, m, userId, cfg) };
      }
      return { ok: true, status: "waiting" };
    }
    case "cancel": {
      await db.queueDelete(userId);
      const m = await db.activeMatchOf(userId);
      const seat = m ? playerOf(m, userId) : null;
      if (m && seat !== null && cfg.now() - Date.parse(m.created_at) < 6e4) {
        const rows = await db.views(m.id, seat, 0);
        if (!rows.some((r) => r.actor === 0 && r.action.type !== "begin")) {
          const w = startWork(m);
          if (applyStep(m, w, seat, { type: "concede" }, cfg).ok === true) await db.saveMatch(m.id, m.steps_count, patchOf({ ...m, end_reason: "concede" }, w, { end_reason: "concede" }), w.steps, w.views);
        }
      }
      return { ok: true, status: "none" };
    }
    case "tick":
    case "act": {
      if (req.op === "act" && (!req.action || typeof req.action.type !== "string" || req.action.type === "begin")) return { ok: false, error: "A\xE7\xE3o inv\xE1lida." };
      for (let attempt = 0; attempt < 3; attempt++) {
        let m = await db.getMatch(req.matchId);
        if (!m) return { ok: false, error: "Partida n\xE3o encontrada." };
        const seat = playerOf(m, userId);
        if (seat === null) return { ok: false, error: "Voc\xEA n\xE3o est\xE1 nessa partida." };
        m = await enforceClock(db, m, cfg);
        if (req.op === "tick" || m.status !== "active") {
          if (req.op === "act") return { ok: false, error: "A partida j\xE1 terminou." };
          const rewards2 = await ensureRewards(db, m);
          return { ok: true, status: "acted", rows: await db.views(m.id, seat, req.since ?? 0), finished: m.status === "finished", deadline: m.turn_deadline, now: cfg.now(), reward: rewardOf(m, rewards2, userId) };
        }
        const w = startWork(m);
        const timeouts = [m.timeouts[0], m.timeouts[1]];
        timeouts[seat] = 0;
        const act = req.action;
        const applied = applyStep(m, w, seat, act, cfg);
        if (applied.ok === false) return { ok: false, error: applied.error };
        runBot(m, w, cfg);
        const endReason = act.type === "concede" ? "concede" : w.state.winner !== null ? "general" : m.end_reason;
        const saved = await db.saveMatch(m.id, m.steps_count, patchOf({ ...m, timeouts }, w, { timeouts, end_reason: endReason }), w.steps, w.views);
        if (!saved) continue;
        const fresh = await db.getMatch(m.id) ?? m;
        const rewards = w.state.winner !== null ? await ensureRewards(db, fresh) : null;
        return { ok: true, status: "acted", rows: await db.views(m.id, seat, req.since ?? 0), finished: w.state.winner !== null, deadline: w.deadline, now: cfg.now(), reward: rewardOf(fresh, rewards, userId) };
      }
      return { ok: false, error: "A partida mudou enquanto voc\xEA jogava. Tente de novo." };
    }
    case "result": {
      const m = await db.getMatch(req.matchId);
      if (!m || playerOf(m, userId) === null) return { ok: false, error: "Partida n\xE3o encontrada." };
      const rewards = await ensureRewards(db, m);
      return { ok: true, status: "result", finished: m.status === "finished", reward: rewardOf(m, rewards, userId) };
    }
    default:
      return { ok: false, error: "Pedido desconhecido." };
  }
};

// server/supabaseDb.ts
var must = (r, what) => {
  if (r.error) throw new Error(`${what}: ${r.error.message ?? r.error}`);
  return r.data;
};
var viewToDb = (matchId, v) => ({
  match_id: matchId,
  n: v.n,
  viewer: v.viewer,
  viewer_user: v.user,
  actor: v.actor,
  action: v.action,
  events: v.events,
  state: v.state,
  deadline: v.deadline
});
var viewFromDb = (r) => ({ n: r.n, viewer: r.viewer, user: r.viewer_user, actor: r.actor, action: r.action, events: r.events, state: r.state, deadline: r.deadline === null ? null : Number(r.deadline) });
var matchFromDb = (r) => ({ ...r, turn_deadline: r.turn_deadline === null || r.turn_deadline === void 0 ? null : Number(r.turn_deadline), timeouts: r.timeouts ?? [0, 0] });
var supabaseDb = (c) => ({
  async collection(userId) {
    const rows = must(await c.from("collection").select("card_name, copies").eq("user_id", userId).limit(5e3), "collection");
    const out = {};
    rows.forEach((r) => {
      out[r.card_name] = r.copies;
    });
    return out;
  },
  async profile(userId) {
    return must(await c.from("profiles").select("username, avatar_id, level, xp, coroas").eq("id", userId).maybeSingle(), "profile");
  },
  async queueTake(excludeUserId) {
    const rows = must(await c.rpc("queue_take", { p_me: excludeUserId }), "queue_take");
    return rows && rows.length ? rows[0] : null;
  },
  async queueGet(userId) {
    return must(await c.from("queue").select("user_id, deck, created_at").eq("user_id", userId).maybeSingle(), "queue get");
  },
  async queuePut(row) {
    must(await c.from("queue").upsert({ user_id: row.user_id, deck: row.deck, created_at: row.created_at }), "queue put");
  },
  async queueDelete(userId) {
    must(await c.from("queue").delete().eq("user_id", userId), "queue delete");
  },
  async createMatch(row, steps, views) {
    const m = matchFromDb(must(await c.from("matches").insert(row).select("*").single(), "create match"));
    if (steps.length) must(await c.from("match_steps").insert(steps.map((s) => ({ match_id: m.id, n: s.n, seat: s.seat, action: s.action }))), "create steps");
    if (views.length) must(await c.from("match_views").insert(views.map((v) => viewToDb(m.id, v))), "create views");
    return m;
  },
  async getMatch(id) {
    const r = must(await c.from("matches").select("*").eq("id", id).maybeSingle(), "get match");
    return r ? matchFromDb(r) : null;
  },
  async activeMatchOf(userId) {
    const rows = must(await c.from("matches").select("*").eq("status", "active").or(`seat0.eq.${userId},seat1.eq.${userId}`).order("created_at", { ascending: false }).limit(1), "active match");
    return rows.length ? matchFromDb(rows[0]) : null;
  },
  async saveMatch(id, expected, patch, newSteps, newViews) {
    if (newSteps.length) {
      const ins = await c.from("match_steps").insert(newSteps.map((s) => ({ match_id: id, n: s.n, seat: s.seat, action: s.action })));
      if (ins.error) return false;
    }
    const upd = must(await c.from("matches").update({
      state: patch.state,
      steps_count: patch.steps_count,
      status: patch.status,
      winner: patch.winner,
      turn_deadline: patch.turn_deadline,
      timeouts: patch.timeouts,
      end_reason: patch.end_reason
    }).eq("id", id).eq("steps_count", expected).select("id"), "save match");
    if (upd.length === 0) {
      if (newSteps.length) await c.from("match_steps").delete().eq("match_id", id).in("n", newSteps.map((s) => s.n));
      return false;
    }
    if (newViews.length) must(await c.from("match_views").upsert(newViews.map((v) => viewToDb(id, v)), { onConflict: "match_id,viewer,n" }), "save views");
    return true;
  },
  async steps(matchId, sinceN) {
    return must(await c.from("match_steps").select("n, seat, action").eq("match_id", matchId).gt("n", sinceN).order("n", { ascending: true }), "steps");
  },
  async views(matchId, viewer, sinceN) {
    const rows = must(await c.from("match_views").select("n, viewer, viewer_user, actor, action, events, state, deadline").eq("match_id", matchId).eq("viewer", viewer).gt("n", sinceN).order("n", { ascending: true }), "views");
    return rows.map(viewFromDb);
  },
  async latestView(matchId, viewer) {
    const rows = must(await c.from("match_views").select("n, viewer, viewer_user, actor, action, events, state, deadline").eq("match_id", matchId).eq("viewer", viewer).order("n", { ascending: false }).limit(1), "latest view");
    return rows.length ? viewFromDb(rows[0]) : null;
  },
  async applyRewards(matchId, rows) {
    return must(await c.rpc("apply_match_rewards", { p_match: matchId, p_rows: rows }), "apply rewards") === true;
  }
});

// server/edge.ts
var cors = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "authorization, x-client-info, apikey, content-type",
  "access-control-allow-methods": "POST, OPTIONS"
};
var json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "content-type": "application/json" } });
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    const url = Deno.env.get("SUPABASE_URL");
    const service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    const admin = createClient(url, service, { auth: { persistSession: false, autoRefreshToken: false } });
    const token = (req.headers.get("authorization") ?? "").replace(/^Bearer\s+/i, "");
    const { data, error } = await admin.auth.getUser(token);
    if (error || !data?.user) return json({ ok: false, error: "Entre na sua conta para jogar online." }, 401);
    const body = await req.json();
    return json(await handleGame(supabaseDb(admin), data.user.id, body));
  } catch (e) {
    console.error("game function error", e);
    return json({ ok: false, error: "Erro no servidor de partidas. Tente de novo." }, 500);
  }
});
