// MOCKUP v2: terreno dos Mercenários (nome provisório "Acampamento de Contratos") — barracas com luz por dentro, fogueira com panela, mercenários sentados, baú de ouro, mesa com livro-caixa, estandarte e bandeirolas; desaba se o terreno cai
(() => {
  const W = innerWidth, H = innerHeight, cv = document.createElement('canvas'); cv.width = W; cv.height = H;
  cv.style.cssText = 'position:fixed;left:0;top:0;width:100%;height:100%;z-index:9999;pointer-events:none'; document.body.appendChild(cv);
  const mc = cv.getContext('2d'), root = document.getElementById('root');
  const mkc = () => { const c = document.createElement('canvas'); c.width = W; c.height = H; return c; }; const scn = mkc(), lgt = mkc(), sc = scn.getContext('2d'), lc2 = lgt.getContext('2d'); let cx = sc;
  const clamp = (v, a = 0, b = 1) => Math.max(a, Math.min(b, v)), easeOut = x => 1 - Math.pow(1 - x, 3), back = x => { const c = 1.7; return 1 + (c + 1) * Math.pow(x - 1, 3) + c * Math.pow(x - 1, 2); };
  let seed = 9; const rnd = () => (seed = (seed * 16807) % 2147483647) / 2147483647;
  let T0 = null, E = null; window.__acampStart = () => { T0 = performance.now(); E = null; }; window.__acampEnd = () => { E = performance.now(); };
  const yG = 724, FX = 196, FY = 712;
  // ── texturas feitas em código (pano, madeira, terra) ──
  const mk = (w, h, f) => { const c = document.createElement('canvas'); c.width = w; c.height = h; f(c.getContext('2d')); return c; };
  const fabric = mk(64, 64, g => { g.fillStyle = '#808080'; g.fillRect(0, 0, 64, 64); for (let i = 0; i < 1400; i++) { g.fillStyle = `rgba(${rnd() < .5 ? 255 : 0},${rnd() < .5 ? 255 : 0},0,0)`; const v = 90 + rnd() * 90; g.fillStyle = `rgb(${v},${v},${v})`; g.fillRect(rnd() * 64, rnd() * 64, 1 + rnd() * 2, 1); } g.strokeStyle = 'rgba(0,0,0,.07)'; g.lineWidth = 1; for (let i = 0; i < 64; i += 2) { g.beginPath(); g.moveTo(0, i + .5); g.lineTo(64, i + .5); g.stroke(); g.beginPath(); g.moveTo(i + .5, 0); g.lineTo(i + .5, 64); g.stroke(); } });
  const wood = mk(64, 32, g => { g.fillStyle = '#808080'; g.fillRect(0, 0, 64, 32); for (let i = 0; i < 90; i++) { const v = 70 + rnd() * 120; g.strokeStyle = `rgba(${v},${v},${v},.7)`; g.lineWidth = .6 + rnd() * 1.2; const y = rnd() * 32; g.beginPath(); g.moveTo(0, y); g.bezierCurveTo(20, y + rnd() * 3 - 1.5, 44, y + rnd() * 3 - 1.5, 64, y + rnd() * 2); g.stroke(); } });
  const dirt = mk(96, 48, g => { g.fillStyle = '#808080'; g.fillRect(0, 0, 96, 48); for (let i = 0; i < 700; i++) { const v = 60 + rnd() * 130; g.fillStyle = `rgb(${v},${v},${v})`; g.beginPath(); g.arc(rnd() * 96, rnd() * 48, .6 + rnd() * 1.8, 0, 7); g.fill(); } });
  const P = {}; const pat = (k, t) => (P[k] || (P[k] = cx.createPattern(t, 'repeat')));
  const tex = (c, t, k, a) => { c.save(); c.globalCompositeOperation = 'soft-light'; c.globalAlpha *= a; c.fillStyle = pat(k, t); c.fillRect(-400, 0, 1200, 800); c.restore(); };
  const rr = (c, x, y, w, h, r) => { c.beginPath(); c.moveTo(x + r, y); c.arcTo(x + w, y, x + w, y + h, r); c.arcTo(x + w, y + h, x, y + h, r); c.arcTo(x, y + h, x, y, r); c.arcTo(x, y, x + w, y, r); c.closePath(); };
  function dust(c, x, y, q, k = 1) { if (q <= 0 || q >= 1) return; const g = c.createRadialGradient(x, y - q * 8, 0, x, y - q * 8, (6 + q * 16) * k); g.addColorStop(0, `rgba(200,180,140,${.3 * (1 - q)})`); g.addColorStop(1, 'rgba(200,180,140,0)'); c.fillStyle = g; c.fillRect(x - 30 * k, y - 40, 60 * k, 56); }
  function glow(c, x, y, r, col, a) { c.save(); c.globalCompositeOperation = 'lighter'; const g = c.createRadialGradient(x, y, 0, x, y, r); g.addColorStop(0, `rgba(${col},${a})`); g.addColorStop(1, `rgba(${col},0)`); c.fillStyle = g; c.fillRect(x - r, y - r, r * 2, r * 2); c.restore(); }
  function flame(c, x, y, t, k, S) { const f = (.75 + .25 * Math.sin(t / 90 + k * 3) + .1 * Math.sin(t / 37 + k)) * S; const h = 13 * f; c.save(); c.globalCompositeOperation = 'lighter';
    let g = c.createRadialGradient(x, y - 4, 0, x, y - 4, 86 * S); g.addColorStop(0, `rgba(255,170,70,${.2 * f})`); g.addColorStop(1, 'rgba(255,150,50,0)'); c.fillStyle = g; c.fillRect(x - 90, y - 90, 180, 150);
    g = c.createRadialGradient(x, y - h * .4, 0, x, y - h * .4, h); g.addColorStop(0, 'rgba(255,248,205,.95)'); g.addColorStop(.4, 'rgba(255,190,80,.8)'); g.addColorStop(1, 'rgba(230,90,20,0)'); c.fillStyle = g; c.beginPath(); c.ellipse(x, y - h * .45, 5, h, 0, 0, 7); c.fill();
    g = c.createRadialGradient(x - 6, y - h * .3, 0, x - 6, y - h * .3, h * .7); g.addColorStop(0, 'rgba(255,220,140,.6)'); g.addColorStop(1, 'rgba(255,130,40,0)'); c.fillStyle = g; c.beginPath(); c.ellipse(x - 5, y - h * .35, 3.6, h * .7, -.2, 0, 7); c.fill(); c.restore(); }
  // ── barraca em 3/4: frente (com porta acesa por dentro) e o plano do telhado; `mir` espelha ──
  function tent(c, o, t, now, dead, td) {
    const q = dead ? 1 : clamp((t - o.ap) / 700); if (q <= 0) return; const squash = dead ? clamp(1 - td * 1.5) : 1; const h = o.h * Math.max(.03, dead ? squash : back(q)); const w = o.fw, dx = o.dx, y = yG, sway = Math.sin(now / 900 + o.k) * .6 * (dead ? 0 : q);
    c.save(); if (o.mir) { c.translate(o.cx * 2, 0); c.scale(-1, 1); }
    const x0 = o.cx - w / 2 - dx / 2, ax = x0 + w / 2 + sway, ay = y - h, ax2 = ax + dx, ay2 = ay - 4 * (h / o.h);
    c.fillStyle = 'rgba(0,0,0,.4)'; c.beginPath(); c.ellipse(x0 + w / 2 + dx / 2, y + 1.5, (w + dx) * .58, 4.2, 0, 0, 7); c.fill();
    // plano do telhado (lado, mais escuro)
    c.save(); c.beginPath(); c.moveTo(ax, ay); c.lineTo(ax2, ay2); c.lineTo(x0 + w + dx, y - 3 * (h / o.h)); c.lineTo(x0 + w, y); c.closePath(); c.clip();
    let g = c.createLinearGradient(ax, ay, x0 + w + dx, y); g.addColorStop(0, o.c2); g.addColorStop(1, '#1d2310'); c.fillStyle = g; c.fillRect(x0, ay2 - 4, w + dx + 4, h + 10); tex(c, fabric, 'f', .85);
    c.strokeStyle = 'rgba(0,0,0,.3)'; c.lineWidth = 1; for (let i = 1; i < 4; i++) { const u = i / 4; c.beginPath(); c.moveTo(ax + (ax2 - ax) * u, ay + (ay2 - ay) * u); c.lineTo(x0 + w + (dx) * u, y - 3 * u * (h / o.h)); c.stroke(); }
    c.fillStyle = o.trim; c.globalAlpha = .75; c.beginPath(); c.moveTo(x0 + w + 1, y - h * .14); c.lineTo(x0 + w + dx, y - 3 - h * .14); c.lineTo(x0 + w + dx, y - 3 * (h / o.h)); c.lineTo(x0 + w, y); c.closePath(); c.fill(); c.restore();
    // frente
    c.save(); c.beginPath(); c.moveTo(ax, ay); c.lineTo(x0, y); c.lineTo(x0 + w, y); c.closePath(); c.clip();
    g = c.createLinearGradient(x0, ay, x0 + w, y); g.addColorStop(0, o.c1); g.addColorStop(1, o.c2); c.fillStyle = g; c.fillRect(x0 - 2, ay - 2, w + 4, h + 4); tex(c, fabric, 'f', 1);
    // dobras do pano
    c.strokeStyle = 'rgba(0,0,0,.22)'; c.lineWidth = 1; for (const u of [-.55, -.25, .25, .55]) { c.beginPath(); c.moveTo(ax, ay); c.quadraticCurveTo(ax + u * w * .5, y - h * .4, ax + u * w * .95, y); c.stroke(); }
    c.strokeStyle = 'rgba(255,240,190,.12)'; for (const u of [-.4, .4]) { c.beginPath(); c.moveTo(ax, ay); c.lineTo(ax + u * w * .95, y); c.stroke(); }
    // faixa de barra e remendo
    c.fillStyle = o.trim; c.globalAlpha = .9; c.beginPath(); c.moveTo(x0 + w * .06, y - h * .14); c.lineTo(x0 + w * .94, y - h * .14); c.lineTo(x0 + w, y); c.lineTo(x0, y); c.closePath(); c.fill(); c.globalAlpha = 1;
    c.fillStyle = 'rgba(70,52,28,.75)'; c.fillRect(ax + w * .18, y - h * .34, 7, 6); c.strokeStyle = 'rgba(230,210,160,.5)'; c.lineWidth = .6; c.setLineDash([1.5, 1.5]); c.strokeRect(ax + w * .18 + .5, y - h * .34 + .5, 6, 5); c.setLineDash([]);
    // porta com luz de dentro
    const doorH = h * .62; c.fillStyle = '#120a05'; c.beginPath(); c.moveTo(ax, y - doorH); c.lineTo(ax + w * .17, y); c.lineTo(ax - w * .17, y); c.closePath(); c.fill();
    const lit = dead ? 0 : clamp((t - o.ap - 500) / 600); g = c.createRadialGradient(ax, y - doorH * .3, 0, ax, y - doorH * .3, w * .22); g.addColorStop(0, `rgba(150,80,30,${.8 * lit})`); g.addColorStop(1, 'rgba(60,30,10,0)'); c.fillStyle = g; c.beginPath(); c.moveTo(ax, y - doorH); c.lineTo(ax + w * .17, y); c.lineTo(ax - w * .17, y); c.closePath(); c.fill();
    c.fillStyle = o.c1; c.beginPath(); c.moveTo(ax, y - doorH - 2); c.lineTo(ax - w * .24, y); c.lineTo(ax - w * .12, y); c.closePath(); c.fill(); c.beginPath(); c.moveTo(ax, y - doorH - 2); c.lineTo(ax + w * .24, y); c.lineTo(ax + w * .12, y); c.closePath(); c.fill(); tex(c, fabric, 'f', .6);
    c.restore();
    // desgaste: manchas de lama e fuligem, rugas macias, sombra no chão
    c.save(); c.beginPath(); c.moveTo(ax, ay); c.lineTo(x0, y); c.lineTo(x0 + w, y); c.closePath(); c.clip();
    let gs = c.createLinearGradient(0, y - h * .5, 0, y); gs.addColorStop(0, 'rgba(25,18,8,0)'); gs.addColorStop(1, 'rgba(25,18,8,.55)'); c.fillStyle = gs; c.fillRect(x0, y - h, w, h);
    for (const [u, v, r] of [[.25, .55, 9], [.7, .4, 7], [.5, .78, 11], [.12, .3, 6]]) { const gx = x0 + w * u, gy = y - h * v, gr = c.createRadialGradient(gx, gy, 0, gx, gy, r); gr.addColorStop(0, 'rgba(30,22,10,.35)'); gr.addColorStop(1, 'rgba(30,22,10,0)'); c.fillStyle = gr; c.fillRect(gx - r, gy - r, r * 2, r * 2); }
    c.lineCap = 'round'; for (const [u, k] of [[-.62, 1], [-.34, .8], [.12, .6], [.4, 1], [.66, .7]]) { c.strokeStyle = 'rgba(0,0,0,.2)'; c.lineWidth = 2.2; c.beginPath(); c.moveTo(ax + u * w * .15, ay + 6); c.quadraticCurveTo(ax + u * w * .55 + k * 3, y - h * .35, ax + u * w * .95, y - 1); c.stroke(); c.strokeStyle = 'rgba(255,245,215,.07)'; c.lineWidth = 1.4; c.beginPath(); c.moveTo(ax + u * w * .15 + 1.5, ay + 6); c.quadraticCurveTo(ax + u * w * .55 + k * 3 + 1.5, y - h * .35, ax + u * w * .95 + 1.5, y - 1); c.stroke(); }
    c.restore();
    // contornos, mastro, cordas e estacas
    c.strokeStyle = 'rgba(12,8,3,.28)'; c.lineWidth = .9; c.beginPath(); c.moveTo(x0 - 1, y); c.lineTo(ax, ay); c.lineTo(x0 + w + 1, y); c.moveTo(ax, ay); c.lineTo(ax2, ay2); c.lineTo(x0 + w + dx, y - 3 * (h / o.h)); c.stroke();
    c.strokeStyle = '#c4a572'; c.lineWidth = .9; for (const [px, py, sx] of [[ax - w * .3, y - h * .35, x0 - 13], [ax2 + 2, ay2 + 6, x0 + w + dx + 12]]) { c.beginPath(); c.moveTo(px, py); c.lineTo(sx, y + 1.5); c.stroke(); c.fillStyle = '#3a2814'; c.fillRect(sx - 1.2, y - 1.5, 2.6, 6); }
    c.strokeStyle = '#2f2012'; c.lineWidth = 1.8; c.beginPath(); c.moveTo(ax, ay); c.lineTo(ax, ay - 13 * q); c.stroke(); c.fillStyle = '#8f7840'; c.beginPath(); c.arc(ax, ay - 13.5 * q, 1.3, 0, 7); c.fill();
    c.restore();
  }
  function crate(c, x, y, w, h, t, ap, dead, td, k) { const q = dead ? 1 : clamp((t - ap) / 320); if (q <= 0) return; const dy = dead ? 0 : (1 - back(q)) * -34; c.save(); c.globalAlpha = clamp(q * 3); c.translate(0, dy);
    c.fillStyle = 'rgba(0,0,0,.3)'; c.beginPath(); c.ellipse(x + w / 2, y + h + 1, w * .6, 2.2, 0, 0, 7); c.fill(); c.save(); rr(c, x, y, w, h, 1.2); c.clip(); const g = c.createLinearGradient(0, y, 0, y + h); g.addColorStop(0, '#a47c48'); g.addColorStop(1, '#5c4022'); c.fillStyle = g; c.fillRect(x, y, w, h); tex(c, wood, 'w', 1);
    c.strokeStyle = 'rgba(25,15,5,.75)'; c.lineWidth = .9; for (let i = 1; i < 3; i++) { c.beginPath(); c.moveTo(x, y + h * i / 3); c.lineTo(x + w, y + h * i / 3); c.stroke(); } c.beginPath(); c.moveTo(x + 1, y + 1); c.lineTo(x + w - 1, y + h - 1); c.stroke(); c.fillStyle = 'rgba(255,230,170,.25)'; c.fillRect(x, y, w, 1.2); c.restore(); c.strokeStyle = 'rgba(15,9,3,.9)'; c.lineWidth = 1; rr(c, x + .5, y + .5, w - 1, h - 1, 1.2); c.stroke();
    if (k) { c.fillStyle = '#e8dcb4'; c.fillRect(x + w * .3, y + h * .25, w * .38, h * .3); c.fillStyle = '#b4372a'; c.beginPath(); c.arc(x + w * .5, y + h * .62, 1.3, 0, 7); c.fill(); } c.restore(); }
  function barrel(c, x, y, w, h, t, ap, dead) { const q = dead ? 1 : clamp((t - ap) / 320); if (q <= 0) return; const dy = dead ? 0 : (1 - back(q)) * -34; c.save(); c.globalAlpha = clamp(q * 3); c.translate(0, dy); c.fillStyle = 'rgba(0,0,0,.3)'; c.beginPath(); c.ellipse(x + w / 2, y + h + 1, w * .62, 2.2, 0, 0, 7); c.fill();
    c.save(); c.beginPath(); c.moveTo(x + 1.5, y); c.quadraticCurveTo(x - 1.5, y + h / 2, x + 1.5, y + h); c.lineTo(x + w - 1.5, y + h); c.quadraticCurveTo(x + w + 1.5, y + h / 2, x + w - 1.5, y); c.closePath(); c.clip(); const g = c.createLinearGradient(x, 0, x + w, 0); g.addColorStop(0, '#5f4122'); g.addColorStop(.4, '#a9814a'); g.addColorStop(1, '#46301a'); c.fillStyle = g; c.fillRect(x - 2, y, w + 4, h); tex(c, wood, 'w', 1); c.strokeStyle = 'rgba(20,12,4,.85)'; c.lineWidth = 1.4; for (const k of [.2, .78]) { c.beginPath(); c.moveTo(x - 2, y + h * k); c.lineTo(x + w + 2, y + h * k); c.stroke(); } c.restore();
    c.fillStyle = '#7a5a30'; c.beginPath(); c.ellipse(x + w / 2, y + .6, w / 2 - 1.2, 1.9, 0, 0, 7); c.fill(); c.strokeStyle = 'rgba(15,9,3,.9)'; c.lineWidth = .8; c.stroke(); c.restore(); }
  function rack(c, x, y, t, ap, dead, now) { const q = dead ? 1 : clamp((t - ap) / 380); if (q <= 0) return; c.save(); c.globalAlpha = clamp(q * 2.5); c.translate(0, dead ? 0 : (1 - back(q)) * -30);
    c.fillStyle = 'rgba(0,0,0,.3)'; c.beginPath(); c.ellipse(x + 11, y + 1, 14, 2.4, 0, 0, 7); c.fill(); c.strokeStyle = '#4a321a'; c.lineWidth = 2; c.beginPath(); c.moveTo(x, y); c.lineTo(x, y - 30); c.moveTo(x + 22, y); c.lineTo(x + 22, y - 30); c.moveTo(x - 1, y - 24); c.lineTo(x + 23, y - 24); c.moveTo(x - 1, y - 9); c.lineTo(x + 23, y - 9); c.stroke();
    c.lineWidth = 1.1; for (let i = 0; i < 4; i++) { const sx = x + 3 + i * 5; c.strokeStyle = '#7d5a30'; c.beginPath(); c.moveTo(sx, y - 1); c.lineTo(sx + (i - 1.5) * .8, y - 33); c.stroke(); c.fillStyle = '#dfe4ec'; c.beginPath(); c.moveTo(sx + (i - 1.5) * .8, y - 36); c.lineTo(sx + (i - 1.5) * .8 - 1.2, y - 32.5); c.lineTo(sx + (i - 1.5) * .8 + 1.2, y - 32.5); c.closePath(); c.fill(); }
    c.strokeStyle = '#b9c0cc'; c.lineWidth = 1.4; for (const sx of [x + 3, x + 8]) { c.beginPath(); c.moveTo(sx, y - 24); c.lineTo(sx, y - 10); c.stroke(); } c.fillStyle = '#c9a24a'; c.fillRect(x + 1.5, y - 24.6, 3, 1.4); c.fillRect(x + 6.5, y - 24.6, 3, 1.4);
    // escudo verde com moeda
    c.fillStyle = '#4c5a24'; c.beginPath(); c.moveTo(x + 12, y - 22); c.lineTo(x + 20, y - 22); c.lineTo(x + 20, y - 15); c.quadraticCurveTo(x + 16, y - 8, x + 12, y - 15); c.closePath(); c.fill(); c.strokeStyle = '#d7a93f'; c.lineWidth = .9; c.stroke(); c.fillStyle = '#e6c15a'; c.beginPath(); c.arc(x + 16, y - 17, 2, 0, 7); c.fill();
    const gl = ((now / 1600) % 1); c.save(); c.globalCompositeOperation = 'lighter'; const gx = x + 3 + gl * 20; const g = c.createRadialGradient(gx, y - 33, 0, gx, y - 33, 5); g.addColorStop(0, `rgba(255,255,255,${.6 * Math.sin(gl * Math.PI)})`); g.addColorStop(1, 'rgba(255,255,255,0)'); c.fillStyle = g; c.fillRect(gx - 5, y - 38, 10, 10); c.restore(); c.restore(); }
  function table(c, x, y, t, ap, dead, now) { const q = dead ? 1 : clamp((t - ap) / 380); if (q <= 0) return; c.save(); c.globalAlpha = clamp(q * 2.5); c.translate(0, dead ? 0 : (1 - back(q)) * -30);
    c.fillStyle = 'rgba(0,0,0,.3)'; c.beginPath(); c.ellipse(x + 11, y + 1, 14, 2.2, 0, 0, 7); c.fill(); c.fillStyle = '#4a321a'; c.fillRect(x + 1, y - 9, 2.2, 9); c.fillRect(x + 19, y - 9, 2.2, 9);
    c.save(); rr(c, x - 1, y - 12, 24, 3.6, 1); c.clip(); const g = c.createLinearGradient(0, y - 12, 0, y - 8); g.addColorStop(0, '#b78d52'); g.addColorStop(1, '#6e4f2a'); c.fillStyle = g; c.fillRect(x - 1, y - 12, 24, 4); tex(c, wood, 'w', 1); c.restore();
    c.fillStyle = '#f0e6c4'; c.beginPath(); c.moveTo(x + 2, y - 12); c.lineTo(x + 9, y - 13.4); c.lineTo(x + 16, y - 12); c.lineTo(x + 9, y - 11); c.closePath(); c.fill(); c.strokeStyle = 'rgba(70,45,20,.8)'; c.lineWidth = .6; c.stroke(); c.beginPath(); c.moveTo(x + 9, y - 13.3); c.lineTo(x + 9, y - 11.2); c.stroke();
    for (let i = 0; i < 3; i++) { c.fillStyle = '#e6c15a'; c.beginPath(); c.ellipse(x + 17.5, y - 12.6 - i * 1.1, 2.3, .9, 0, 0, 7); c.fill(); c.strokeStyle = 'rgba(100,60,5,.8)'; c.lineWidth = .5; c.stroke(); }
    c.fillStyle = '#efe5c8'; c.fillRect(x + 1.3, y - 18, 2.2, 6); const f = .85 + .15 * Math.sin(now / 90 + 2); c.fillStyle = `rgba(255,214,120,${f})`; c.beginPath(); c.ellipse(x + 2.4, y - 19.6, 1, 2.1 * f, 0, 0, 7); c.fill(); c.restore(); if (!dead) glow(c, x + 2.4, y - 18, 20, '255,190,90', .22 * clamp(q)); }
  function chest(c, x, y, t, ap, dead, now) { const q = dead ? 1 : clamp((t - ap) / 380); if (q <= 0) return; c.save(); c.globalAlpha = clamp(q * 2.5); c.translate(0, dead ? 0 : (1 - back(q)) * -30);
    c.fillStyle = 'rgba(0,0,0,.3)'; c.beginPath(); c.ellipse(x + 9, y + 1, 12, 2.2, 0, 0, 7); c.fill();
    // ouro transbordando
    c.fillStyle = '#e9c25a'; for (let i = 0; i < 9; i++) { c.beginPath(); c.ellipse(x + 3 + i * 1.6, y - 11 - Math.sin(i * 1.7) * 1.4, 2.1, 1.2, 0, 0, 7); c.fill(); }
    c.save(); rr(c, x, y - 11, 18, 11, 1.6); c.clip(); const g = c.createLinearGradient(0, y - 11, 0, y); g.addColorStop(0, '#8a5f30'); g.addColorStop(1, '#4e3419'); c.fillStyle = g; c.fillRect(x, y - 11, 18, 11); tex(c, wood, 'w', 1); c.fillStyle = '#2b2118'; c.fillRect(x + 1, y - 11, 2, 11); c.fillRect(x + 15, y - 11, 2, 11); c.fillRect(x, y - 6, 18, 1.6); c.fillStyle = '#d7a93f'; c.fillRect(x + 7.5, y - 7.4, 3, 3.6); c.restore(); c.strokeStyle = 'rgba(12,8,3,.9)'; c.lineWidth = 1; rr(c, x + .5, y - 10.5, 17, 10, 1.6); c.stroke();
    c.save(); c.translate(x + 9, y - 11); c.rotate(-.5); c.fillStyle = '#6e4a24'; rr(c, -9, -5, 18, 5, 1.6); c.fill(); c.strokeStyle = 'rgba(12,8,3,.9)'; c.lineWidth = .9; c.stroke(); c.restore(); c.restore();
    if (!dead) { glow(c, x + 9, y - 13, 26, '255,200,90', (.22 + .06 * Math.sin(now / 600)) * clamp(q)); const k = (now / 1300) % 1, gx = x + 3 + k * 12; if (k < .5) { c.save(); c.globalCompositeOperation = 'lighter'; for (const [dx, dy] of [[1, 0], [0, 1]]) { const g2 = c.createLinearGradient(gx - dx * 5, y - 14 - dy * 5, gx + dx * 5, y - 14 + dy * 5); g2.addColorStop(0, 'rgba(255,230,160,0)'); g2.addColorStop(.5, `rgba(255,250,220,${Math.sin(k * 2 * Math.PI) * .95})`); g2.addColorStop(1, 'rgba(255,230,160,0)'); c.strokeStyle = g2; c.lineWidth = 1.3; c.beginPath(); c.moveTo(gx - dx * 5, y - 14 - dy * 5); c.lineTo(gx + dx * 5, y - 14 + dy * 5); c.stroke(); } c.restore(); } } }
  // mercenário (sentado ou andando); dir: +1 olha para a direita
  function merc(c, x, y, dir, now, ph, seated, walk, col) { c.save(); c.translate(x, y); c.scale(dir, 1); const bob = walk ? Math.abs(Math.sin(now / 90 + ph)) * 1.2 : 0; c.translate(0, -bob);
    c.fillStyle = 'rgba(0,0,0,.32)'; c.beginPath(); c.ellipse(0, bob + 1, 5.5, 1.5, 0, 0, 7); c.fill();
    if (seated) { c.fillStyle = '#3a281a'; c.fillRect(-3.4, -4.4, 8.8, 2.2); c.fillStyle = '#2a2018'; c.fillRect(1.4, -4.4, 5.4, 2.6); c.fillRect(5.4, -2.2, 1.8, 2.2); }
    else { const sw = Math.sin(now / 90 + ph) * 2; c.fillStyle = '#2a2018'; c.fillRect(-2.2 + sw * .4, -4.6, 1.9, 4.6); c.fillRect(.3 - sw * .4, -4.6, 1.9, 4.6); }
    const ty = seated ? -5 : -4.4; c.fillStyle = col; c.beginPath(); c.moveTo(-3.6, ty); c.lineTo(3.2, ty); c.lineTo(3.8, ty - 7); c.lineTo(-3.2, ty - 7); c.closePath(); c.fill(); c.fillStyle = 'rgba(0,0,0,.28)'; c.fillRect(-3.4, ty - 3.2, 6.8, 1.1); c.fillStyle = '#c9a24a'; c.fillRect(-.5, ty - 3.4, 1.4, 1.6);
    const raise = seated ? Math.max(0, Math.sin(now / 1100 + ph)) : 0; c.strokeStyle = col; c.lineWidth = 1.8; c.lineCap = 'round'; c.beginPath(); c.moveTo(2.6, ty - 5.4); c.lineTo(5 + raise * -1, ty - 3 - raise * 4); c.stroke(); c.fillStyle = '#8a8272'; c.fillRect(4.2 - raise, ty - 5 - raise * 4, 2.2, 2.4);
    c.fillStyle = '#7a5a40'; c.beginPath(); c.arc(.4, ty - 9.2, 2.1, 0, 7); c.fill(); c.fillStyle = '#2e2416'; c.beginPath(); c.arc(.1, ty - 9.8, 2.5, Math.PI * .95, Math.PI * 2.05); c.fill(); c.fillRect(-2.4, ty - 9.6, 1.3, 2.4);
    c.fillStyle = '#a7adb7'; c.fillRect(-4.6, ty - 5.2, 1.2, 6); c.restore(); }
  function frame(now) {
    requestAnimationFrame(frame); mc.clearRect(0, 0, W, H); sc.clearRect(0, 0, W, H); cx = sc; if (T0 == null) { root && (root.style.transform = ''); return; }
    const t = now - T0, te = E ? now - E : -1; if (te > 2400) { root && (root.style.transform = ''); return; }
    const dead = te >= 0, td = dead ? te / 1000 : 0;
    let sh = 0; for (const ts of [1050, 1350, 1800, 1950, 2100]) { const d = t - ts; if (d > 0 && d < 240) sh = Math.max(sh, (1 - d / 240) * .8); } if (dead && te < 400) sh = Math.max(sh, (1 - te / 400) * 1.2);
    if (root) root.style.transform = sh > .05 ? `translate(${(Math.sin(now / 17) * sh).toFixed(2)}px,${(Math.cos(now / 23) * sh).toFixed(2)}px)` : '';
    const fade = dead ? clamp(1 - td / 1.6) : 1;
    const fire = dead ? clamp(1 - te / 800) : easeOut(clamp((t - 2200) / 700)), flick = .88 + .08 * Math.sin(now / 95) + .05 * Math.sin(now / 41);
    // ───────── CENA (desenhada sem luz; a luz entra depois) ─────────
    const gi = clamp(t / 900) * fade; if (gi > 0) {
      if (!window.__dl) { const l = document.createElement('canvas'); l.width = W; l.height = 60; window.__dl = l; }
      const l = window.__dl, lc = l.getContext('2d'); lc.globalCompositeOperation = 'source-over'; lc.clearRect(0, 0, W, 60); lc.fillStyle = '#3a2819'; lc.fillRect(0, 0, W, 60); lc.save(); lc.globalCompositeOperation = 'soft-light'; lc.fillStyle = pat('d', dirt); lc.fillRect(0, 0, W, 60); lc.restore();
      lc.globalCompositeOperation = 'destination-in'; lc.save(); lc.translate(195, 34); lc.scale(1, .13); const gg = lc.createRadialGradient(0, 0, 0, 0, 0, 215); gg.addColorStop(0, 'rgba(0,0,0,.85)'); gg.addColorStop(.7, 'rgba(0,0,0,.5)'); gg.addColorStop(1, 'rgba(0,0,0,0)'); lc.fillStyle = gg; lc.fillRect(-220, -260, 440, 520); lc.restore();
      cx.save(); cx.globalAlpha = gi * .8; cx.drawImage(l, 0, yG - 34); cx.globalAlpha = gi; cx.strokeStyle = 'rgba(170,150,90,.4)'; cx.lineWidth = .8; for (let i = 0; i < 26; i++) { const sx = 20 + (i * 53 % 350), sy = yG - 10 + (i * 17 % 14); cx.beginPath(); cx.moveTo(sx, sy); cx.lineTo(sx + 3 + (i % 3), sy - 1.2 + (i % 2)); cx.stroke(); } cx.restore(); }
    if (!dead) { const stakes = 11; for (let i = 0; i < stakes; i++) { const sx = 100 + i * 19.6, ap = 250 + i * 65, q = clamp((t - ap) / 220); if (q <= 0) continue; const y0 = yG + 2 - (1 - back(q)) * 12; cx.fillStyle = '#3a2819'; cx.fillRect(sx - 1.4, y0 - 12, 2.8, 14); cx.fillStyle = 'rgba(210,180,130,.25)'; cx.fillRect(sx - 1.4, y0 - 12, 1, 14); dust(cx, sx, yG + 2, (t - ap - 160) / 650, .6); }
      const rope = clamp((t - 700) / 800); if (rope > 0) { cx.strokeStyle = '#8f7650'; cx.lineWidth = 1.3; cx.beginPath(); const n = Math.floor(rope * (stakes - 1)); for (let i = 0; i < n; i++) { const ax = 100 + i * 19.6, bx = ax + 19.6; cx.moveTo(ax, yG - 9); cx.quadraticCurveTo((ax + bx) / 2, yG - 4, bx, yG - 9); } cx.stroke(); } }
    const TA = { cx: 56, fw: 62, dx: 26, h: 48, ap: 900, c1: '#80835a', c2: '#383d28', trim: '#8f7840', k: 0 }, TB = { cx: 332, fw: 62, dx: 26, h: 52, ap: 1200, c1: '#878a5c', c2: '#3c422a', trim: '#8f7840', k: 1.7, mir: true };
    const fall = (fn, i, cxm, cym) => { if (!dead) { fn(); return; } const q = Math.max(0, td - (i % 5) * .05), a = clamp(1 - (q - .1) / 1.1); if (a <= 0) return; cx.save(); cx.globalAlpha = a; cx.translate((i % 2 ? 1 : -1) * 40 * q, 380 * q * q - 50 * q); cx.translate(cxm, cym); cx.rotate((i % 2 ? 1 : -1) * 2 * q); cx.translate(-cxm, -cym); fn(); cx.restore(); };
    fall(() => tent(cx, TA, t, now, dead, td), 1, 56, yG - 20); fall(() => tent(cx, TB, t, now, dead, td), 2, 332, yG - 20);
    fall(() => rack(cx, 102, yG, t, 1550, dead, now), 3, 113, yG - 15); fall(() => crate(cx, 128, yG - 13, 15, 13, t, 1700, dead, td, 1), 4, 135, yG); fall(() => crate(cx, 130, yG - 24, 12, 11, t, 1840, dead, td, 0), 5, 136, yG - 20); fall(() => barrel(cx, 146, yG - 18, 14, 18, t, 1770, dead), 6, 153, yG - 9);
    fall(() => table(cx, 232, yG, t, 1650, dead, now), 7, 243, yG - 8); fall(() => chest(cx, 258, yG, t, 1800, dead, now), 8, 267, yG - 6); fall(() => crate(cx, 278, yG - 14, 15, 14, t, 1900, dead, td, 1), 9, 285, yG - 7);
    if (!dead) { for (const [x, ap] of [[135, 1700], [285, 1900], [113, 1550], [243, 1650], [267, 1800], [153, 1770]]) dust(cx, x, yG, (t - ap - 260) / 900, 1.2); for (const [x, ap] of [[56, 900], [332, 1200]]) dust(cx, x, yG, (t - ap - 400) / 1100, 2.2); }
    const logs = clamp((t - 2000) / 300) * fade; if (logs > 0) { cx.save(); cx.globalAlpha = logs; cx.fillStyle = 'rgba(0,0,0,.45)'; cx.beginPath(); cx.ellipse(FX, FY + 4, 24, 5.4, 0, 0, 7); cx.fill();
      for (let i = 0; i < 8; i++) { const a = i / 8 * 6.283, sx = FX + Math.cos(a) * 16, sy = FY + 3 + Math.sin(a) * 3.3; cx.fillStyle = i % 2 ? '#5a564e' : '#736e63'; cx.beginPath(); cx.ellipse(sx, sy, 4.2, 2.9, 0, 0, 7); cx.fill(); }
      for (const [dx, rot] of [[-1, -.35], [1, .35]]) { cx.save(); cx.translate(FX + dx * 2, FY + 1); cx.rotate(rot); cx.fillStyle = '#2e1f12'; cx.fillRect(-12, -2.4, 24, 4.8); cx.restore(); }
      cx.strokeStyle = '#241910'; cx.lineWidth = 1.5; cx.beginPath(); cx.moveTo(FX - 13, FY + 4); cx.lineTo(FX, FY - 26); cx.lineTo(FX + 13, FY + 4); cx.stroke(); cx.strokeStyle = '#17100a'; cx.lineWidth = .9; cx.beginPath(); cx.moveTo(FX, FY - 26); cx.lineTo(FX, FY - 19); cx.stroke(); cx.fillStyle = '#1e1b18'; cx.beginPath(); cx.ellipse(FX, FY - 14, 6.4, 5.6, 0, 0, Math.PI); cx.lineTo(FX - 6.4, FY - 14); cx.fill(); cx.fillStyle = '#35302a'; cx.beginPath(); cx.ellipse(FX, FY - 14, 6.4, 1.8, 0, 0, 7); cx.fill(); cx.restore(); }
    { const seats = [{ x: 172, from: -20, dir: 1, ap: 2300, col: '#2a2f1c', ph: 0 }, { x: 222, from: 410, dir: -1, ap: 2500, col: '#3a2e1c', ph: 2.2 }];
      for (const m of seats) { const walkT = 1500, tw = t - m.ap; if (tw < 0) continue; if (dead) { const q = Math.max(0, te - 120) / 1000, xx = m.x + (m.dir > 0 ? -1 : 1) * q * 260 * (1 + q); if (xx < -20 || xx > 410) continue; merc(cx, xx, yG - 1, -m.dir, now, m.ph, false, true, m.col); continue; }
        const wp = clamp(tw / walkT); if (wp < 1) { const xx = m.from + (m.x - m.from) * easeOut(wp); merc(cx, xx, yG - 1, m.dir, now, m.ph, false, true, m.col); }
        else { cx.fillStyle = '#34240f'; cx.beginPath(); cx.ellipse(m.x, yG - 2, 8, 2.8, 0, 0, 7); cx.fill(); merc(cx, m.x, yG - 1.4, m.dir, now, m.ph, true, false, m.col); } } }
    { const q = dead ? 0 : clamp((t - 2900) / 900); if (q > 0 || (dead && te < 600)) { const ax = 69, ay = yG - 51, bx = 319, by = yG - 55; const n = 22; cx.save(); cx.globalAlpha = dead ? clamp(1 - te / 500) : 1; cx.strokeStyle = '#2a1d10'; cx.lineWidth = .9; cx.beginPath(); const pts = []; for (let i = 0; i <= n; i++) { const u = i / n, x = 40 + (350 - 40) * u, sag = Math.sin(u * Math.PI) * 11; pts.push([x, ay + (by - ay) * u + sag]); } const shown = Math.floor(q * n); cx.moveTo(pts[0][0], pts[0][1]); for (let i = 1; i <= shown; i++) cx.lineTo(pts[i][0], pts[i][1]); cx.stroke();
        for (let i = 1; i <= shown; i += 1) { const [x, y] = pts[i]; const cols = ['#4f5334', '#8a7440', '#a39a80']; const wob = Math.sin(now / 260 + i * .9) * 1.4; cx.fillStyle = cols[i % 3]; cx.beginPath(); cx.moveTo(x - 3, y); cx.lineTo(x + 3, y); cx.lineTo(x + wob * .5, y + 6.5); cx.closePath(); cx.fill(); } cx.restore(); } }
    { const q = dead ? 0 : clamp((t - 2700) / 800); const bx = 150, by = yG - 4; if (q > 0 || (dead && te < 900)) { const rise = dead ? 1 - clamp(te / 600) : easeOut(q); cx.save(); cx.globalAlpha = dead ? clamp(1 - te / 800) : 1; cx.strokeStyle = '#6e5430'; cx.lineWidth = 2.2; cx.beginPath(); cx.moveTo(bx, by); cx.lineTo(bx, by - 54 * rise); cx.stroke(); if (rise > .5) { const f = clamp((rise - .5) / .5), top = by - 54; cx.beginPath(); cx.moveTo(bx, top + 2); for (let i = 0; i <= 8; i++) { const u = i / 8; cx.lineTo(bx + u * 24 * f, top + 2 + Math.sin(now / 240 - u * 3.2) * 2.2 * u); } for (let i = 8; i >= 0; i--) { const u = i / 8; cx.lineTo(bx + u * 24 * f, top + 21 + Math.sin(now / 240 - u * 3.2) * 2.2 * u); } cx.closePath(); const g = cx.createLinearGradient(bx, 0, bx + 24, 0); g.addColorStop(0, '#5a5f3a'); g.addColorStop(1, '#2d3220'); cx.fillStyle = g; cx.fill(); cx.save(); cx.clip(); tex(cx, fabric, 'f', 1); cx.restore(); cx.fillStyle = '#b79a4c'; cx.beginPath(); cx.arc(bx + 10 * f, top + 11 + Math.sin(now / 240 - 1.4) * 1, 4.4 * f, 0, 7); cx.fill(); cx.strokeStyle = 'rgba(70,45,5,.8)'; cx.lineWidth = .8; cx.stroke(); } cx.restore(); } }
    // ───────── LUZ: escurece tudo (noite) e acende só o que a fogueira, as portas, a vela e o ouro iluminam ─────────
    sc.save(); sc.globalCompositeOperation = 'source-atop'; sc.fillStyle = 'rgba(14,16,30,.36)'; sc.fillRect(0, 0, W, H); sc.restore();
    lc2.clearRect(0, 0, W, H); lc2.globalCompositeOperation = 'source-over'; lc2.drawImage(scn, 0, 0); lc2.globalCompositeOperation = 'source-in';
    const L = (x, y, r, rgb, a) => { const g = lc2.createRadialGradient(x, y, 0, x, y, r); g.addColorStop(0, `rgba(${rgb},${a})`); g.addColorStop(.5, `rgba(${rgb},${a * .45})`); g.addColorStop(1, `rgba(${rgb},0)`); lc2.fillStyle = g; lc2.fillRect(x - r, y - r, r * 2, r * 2); };
    const lt = [];
    if (fire > .02) lt.push([FX, FY - 8, 200, '255,150,60', 1 * fire * flick]);
    if (!dead) { lt.push([232 + 2.4, yG - 18, 34, '255,190,100', .55 * clamp((t - 1650) / 400)], [267, yG - 12, 30, '255,205,100', .6 * clamp((t - 1800) / 400) * (.9 + .1 * Math.sin(now / 600))]);
      for (const o of [TA, TB]) { const w = o.fw, dx = o.dx, x0 = o.cx - w / 2 - dx / 2, axp = x0 + w / 2, ax = o.mir ? o.cx * 2 - axp : axp, a = clamp((t - o.ap - 500) / 600) * (.85 + .1 * Math.sin(now / 130 + o.k * 2)); lt.push([ax, yG - 14, 52, '255,150,60', .9 * a], [ax + (o.mir ? -6 : 6), yG - 30, 70, '120,140,200', .22]); } }
    for (const l of lt) L(...l);
    lc2.globalCompositeOperation = 'source-over';
    // ───────── composição: cena escurecida (levemente suavizada) + luz somada + brilho ─────────
    mc.save(); mc.filter = 'blur(.45px)'; mc.drawImage(scn, 0, 0); mc.restore();
    mc.save(); mc.globalCompositeOperation = 'lighter'; mc.drawImage(lgt, 0, 0); mc.filter = 'blur(5px)'; mc.globalAlpha = .55; mc.drawImage(lgt, 0, 0); mc.restore();
    cx = mc;
    // ───────── EFEITOS DE LUZ (somados por cima) ─────────
    if (fire > .02) { flame(mc, FX, FY - 1, now, 3, fire);
      mc.save(); mc.globalCompositeOperation = 'lighter'; for (let i = 0; i < 10; i++) { const ph = ((now / 1500 + i * .137) % 1), x = FX + Math.sin(now / 400 + i * 2.3) * (6 + ph * 14), y = FY - 8 - ph * 58, a = (1 - ph) * .85 * fire; mc.fillStyle = `rgba(255,${150 + ph * 80},70,${a})`; mc.beginPath(); mc.arc(x, y, 1.1 * (1 - ph * .5) + .3, 0, 7); mc.fill(); } mc.restore();
      for (let i = 0; i < 4; i++) { const ph = ((now / 4200 + i * .25) % 1), x = FX + Math.sin(now / 1300 + i * 1.7) * 9 + ph * 12, y = FY - 24 - ph * 46, a = Math.sin(ph * Math.PI) * .09 * fire; const g = mc.createRadialGradient(x, y, 0, x, y, 12 + ph * 12); g.addColorStop(0, `rgba(170,160,150,${a})`); g.addColorStop(1, 'rgba(170,160,150,0)'); mc.fillStyle = g; mc.beginPath(); mc.arc(x, y, 12 + ph * 12, 0, 7); mc.fill(); }
      if (!dead) for (let i = 0; i < 3; i++) { const ph = ((now / 1800 + i * .33) % 1), x = FX + Math.sin(ph * 6 + i) * 3, y = FY - 20 - ph * 22, a = Math.sin(ph * Math.PI) * .2 * fire; const g = mc.createRadialGradient(x, y, 0, x, y, 6 + ph * 5); g.addColorStop(0, `rgba(225,225,220,${a})`); g.addColorStop(1, 'rgba(225,225,220,0)'); mc.fillStyle = g; mc.beginPath(); mc.arc(x, y, 6 + ph * 5, 0, 7); mc.fill(); } }
    if (!dead) { const cf = .85 + .15 * Math.sin(now / 90 + 2); glow(mc, 234.4, yG - 20, 7, '255,214,120', .75 * cf * clamp((t - 1650) / 400)); const k = (now / 1300) % 1, gx = 261 + k * 12; if (k < .5 && t > 1900) { mc.save(); mc.globalCompositeOperation = 'lighter'; for (const [dx, dy] of [[1, 0], [0, 1]]) { const g2 = mc.createLinearGradient(gx - dx * 5, yG - 14 - dy * 5, gx + dx * 5, yG - 14 + dy * 5); g2.addColorStop(0, 'rgba(255,230,160,0)'); g2.addColorStop(.5, `rgba(255,250,220,${Math.sin(k * 2 * Math.PI) * .9})`); g2.addColorStop(1, 'rgba(255,230,160,0)'); mc.strokeStyle = g2; mc.lineWidth = 1.2; mc.beginPath(); mc.moveTo(gx - dx * 5, yG - 14 - dy * 5); mc.lineTo(gx + dx * 5, yG - 14 + dy * 5); mc.stroke(); } mc.restore(); } }
    if (dead && te < 1400) { const q = te / 1400; for (let i = 0; i < 5; i++) { const x = FX + (i - 2) * 6, y = FY - 10 - q * 40 - i * 3, a = (1 - q) * .2; const g = mc.createRadialGradient(x, y, 0, x, y, 14 + q * 12); g.addColorStop(0, `rgba(150,145,135,${a})`); g.addColorStop(1, 'rgba(150,145,135,0)'); mc.fillStyle = g; mc.beginPath(); mc.arc(x, y, 14 + q * 12, 0, 7); mc.fill(); } }
    const s = document.getElementById('player-11'); if (s && !dead) { const r = s.getBoundingClientRect(), a = clamp((t - 300) / 700); mc.save(); mc.shadowColor = 'rgba(255,196,90,.9)'; mc.shadowBlur = 8 + 3 * Math.sin(t / 900); mc.strokeStyle = `rgba(240,205,120,${a * (.3 + .08 * Math.sin(t / 900))})`; mc.lineWidth = 1.6; rr(mc, r.x - 3, r.y - 3, r.width + 6, r.height + 6, 8); mc.stroke(); mc.restore(); }
  }
  requestAnimationFrame(frame);
})();
